insert into AlbumType (catalogueNo, formatName, recordMethod) values (1, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (2, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (3, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (4, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (5, 'Compact Casset', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (6, 'Compact Casset', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (7, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (8, 'Compact Casset', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (9, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (10, '8-Track Tape', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (11, '8-Track Tape', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (12, 'Compact Disc CD', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (13, 'Compact Disc CD', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (14, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (15, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (16, 'Compact Disc CD', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (17, 'Vinyl Record', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (18, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (19, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (20, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (21, 'Compact Casset', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (22, '8-Track Tape', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (23, '8-Track Tape', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (24, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (25, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (26, '8-Track Tape', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (27, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (28, '8-Track Tape', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (29, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (30, 'Compact Casset', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (31, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (32, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (33, 'Vinyl Record', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (34, 'Vinyl Record', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (35, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (36, 'Vinyl Record', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (37, 'Compact Casset', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (38, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (39, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (40, 'Floppy Disk', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (41, 'Compact Disc CD', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (42, 'Compact Disc CD', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (43, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (44, '8-Track Tape', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (45, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (46, 'Compact Casset', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (47, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (48, 'Vinyl Record', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (49, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (50, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (51, 'Compact Disc CD', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (52, 'Floppy Disk', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (53, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (54, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (55, 'Compact Disc CD', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (56, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (57, 'Compact Disc CD', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (58, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (59, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (60, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (61, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (62, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (63, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (64, 'Compact Disc CD', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (65, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (66, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (67, 'Compact Casset', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (68, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (69, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (70, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (71, 'Compact Disc CD', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (72, '8-Track Tape', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (73, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (74, 'Compact Disc CD', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (75, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (76, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (77, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (78, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (79, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (80, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (81, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (82, 'Compact Disc CD', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (83, 'Compact Casset', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (84, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (85, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (86, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (87, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (88, 'Floppy Disk', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (89, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (90, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (91, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (92, 'Compact Disc CD', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (93, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (94, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (95, '8-Track Tape', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (96, 'Compact Casset', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (97, '8-Track Tape', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (98, 'Floppy Disk', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (99, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (100, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (101, 'Compact Casset', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (102, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (103, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (104, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (105, '8-Track Tape', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (106, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (107, '8-Track Tape', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (108, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (109, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (110, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (111, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (112, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (113, 'Vinyl Record', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (114, 'Compact Casset', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (115, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (116, 'Compact Casset', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (117, 'Vinyl Record', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (118, 'Floppy Disk', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (119, 'Floppy Disk', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (120, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (121, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (122, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (123, '8-Track Tape', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (124, '8-Track Tape', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (125, 'Compact Disc CD', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (126, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (127, 'Vinyl Record', 'Cover');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (128, 'Floppy Disk', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (129, '8-Track Tape', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (130, 'Compact Disc CD', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (131, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (132, 'Floppy Disk', 'Live');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (133, 'Floppy Disk', 'Studio');
insert into AlbumType (catalogueNo, formatName, recordMethod) values (134, 'Vinyl Record', 'Studio');
