insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('incentivize cross-platform supply-chains', 10.84, 5, '1863-11-06', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('synthesize compelling web services', 12.04, 6, '1925-12-19', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('extend integrated portals', 31.62, 3, '1855-03-08', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('mesh e-business eyeballs', 21.85, 2, '1938-03-04', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('maximize interactive e-commerce', 39.44, 2, '1838-08-28', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('unleash one-to-one infrastructures', 15.08, 4, '1833-08-17', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('visualize robust web-readiness', 37.7, 1, '1887-05-31', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('leverage seamless systems', 31.85, 3, '1854-04-17', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('scale impactful infrastructures', 30.93, 4, '1889-05-17', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('innovate open-source infrastructures', 13.94, 4, '1948-01-02', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('mesh back-end models', 39.46, 2, '1834-12-15', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('harness strategic e-business', 13.21, 1, '1849-10-07', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('reinvent 24/365 networks', 35.21, 2, '1937-06-01', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('whiteboard value-added networks', 12.96, 6, '1888-11-29', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('drive world-class infrastructures', 39.37, 4, '1967-07-09', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('scale scalable e-commerce', 10.36, 2, '1916-06-29', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('engineer out-of-the-box e-markets', 13.74, 6, '1839-04-29', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('harness sticky platforms', 19.43, 2, '1942-09-28', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('facilitate best-of-breed ROI', 11.52, 3, '1908-01-31', 'EDM');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('target magnetic systems', 10.14, 3, '1922-01-25', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('redefine B2B bandwidth', 35.77, 1, '1886-01-15', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('aggregate sticky ROI', 32.91, 1, '1869-03-29', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('unleash value-added vortals', 36.53, 4, '1930-11-22', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('deliver visionary initiatives', 38.21, 4, '1874-10-04', 'EDM');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('engage best-of-breed networks', 32.28, 6, '1992-07-12', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('visualize B2C deliverables', 29.33, 1, '1978-01-07', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('deploy integrated convergence', 14.74, 6, '1928-11-17', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('benchmark visionary bandwidth', 23.51, 5, '1875-05-23', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('synthesize B2B ROI', 14.42, 5, '1973-01-13', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('utilize viral solutions', 36.45, 1, '1979-01-31', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('iterate user-centric architectures', 12.57, 5, '1854-07-20', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('iterate scalable systems', 36.62, 3, '1842-10-04', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('optimize one-to-one architectures', 32.76, 4, '1839-02-25', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('integrate turn-key infrastructures', 18.06, 4, '1941-09-26', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('monetize out-of-the-box infrastructures', 12.9, 2, '1860-08-19', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('visualize front-end e-tailers', 19.96, 1, '1963-05-14', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('facilitate turn-key channels', 23.77, 6, '1868-07-10', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('envisioneer proactive convergence', 20.11, 1, '1992-02-07', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('enable innovative schemas', 37.65, 6, '1923-03-27', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('target impactful systems', 17.3, 5, '1925-12-02', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('innovate killer architectures', 21.56, 6, '1950-10-17', 'EDM');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('visualize e-business deliverables', 25.39, 4, '1851-03-06', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('engage cross-media bandwidth', 31.72, 6, '1855-11-13', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('benchmark best-of-breed functionalities', 35.57, 2, '1896-03-23', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('monetize back-end solutions', 33.6, 5, '1960-01-31', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('innovate robust applications', 17.07, 6, '1876-12-07', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('strategize dynamic infrastructures', 21.39, 4, '1915-03-18', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('exploit 24/7 paradigms', 38.43, 5, '1878-12-13', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('revolutionize cross-media users', 34.04, 5, '1847-04-29', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('visualize magnetic e-tailers', 33.18, 5, '1900-03-27', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('harness 24/365 e-commerce', 13.0, 1, '1942-09-21', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('redefine one-to-one infomediaries', 10.66, 2, '1926-09-14', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('monetize synergistic infrastructures', 35.65, 4, '1891-08-15', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('enhance B2C ROI', 21.05, 2, '1831-09-07', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('revolutionize customized schemas', 26.77, 5, '1962-07-12', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('streamline clicks-and-mortar paradigms', 15.78, 6, '1838-02-08', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('reintermediate value-added action-items', 10.79, 5, '2000-01-14', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('maximize front-end markets', 19.28, 6, '1930-05-26', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('facilitate turn-key e-services', 22.27, 4, '1988-03-31', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('engineer cross-media networks', 12.43, 4, '1871-08-14', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('deliver back-end metrics', 18.77, 4, '1841-02-28', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('utilize 24/365 web-readiness', 30.68, 5, '1887-01-27', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('implement B2B methodologies', 14.69, 3, '1933-09-29', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('repurpose bleeding-edge networks', 32.46, 1, '1922-03-12', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('cultivate mission-critical solutions', 16.28, 1, '1872-07-17', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('evolve revolutionary methodologies', 33.48, 6, '1871-05-15', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('e-enable real-time interfaces', 17.01, 3, '1907-05-25', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('aggregate bricks-and-clicks users', 38.76, 1, '1990-04-12', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('exploit cross-media initiatives', 10.19, 5, '1836-05-12', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('enhance integrated interfaces', 12.65, 4, '1932-01-19', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('synergize B2C schemas', 13.44, 4, '1952-06-28', 'EDM');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('synergize interactive relationships', 39.5, 2, '1869-06-12', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('exploit robust metrics', 30.07, 1, '1847-10-25', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('innovate frictionless content', 36.25, 4, '1981-03-03', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('productize sexy content', 14.05, 5, '1957-01-19', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('synergize dot-com architectures', 20.7, 6, '1863-06-19', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('seize collaborative systems', 18.53, 1, '1935-01-18', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('brand integrated markets', 18.24, 6, '1833-02-18', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('empower real-time metrics', 37.8, 1, '1983-03-07', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('seize 24/365 web services', 29.39, 6, '1866-08-17', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('enable distributed vortals', 29.78, 2, '1842-05-18', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('benchmark user-centric metrics', 38.88, 5, '1936-05-14', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('facilitate 24/365 mindshare', 32.88, 6, '1951-08-23', 'EDM');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('transform interactive mindshare', 28.21, 3, '1849-02-26', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('transform web-enabled e-tailers', 35.07, 3, '1833-05-21', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('maximize revolutionary experiences', 10.79, 4, '1883-05-30', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('recontextualize synergistic communities', 18.86, 1, '1947-02-04', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('synthesize bricks-and-clicks functionalities', 34.97, 6, '1999-06-04', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('engineer B2B ROI', 12.5, 6, '1999-04-29', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('strategize seamless web-readiness', 15.74, 6, '1854-07-31', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('integrate enterprise channels', 21.96, 3, '1896-06-17', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('expedite next-generation markets', 17.16, 1, '1904-12-17', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('embrace innovative methodologies', 26.06, 2, '1887-02-17', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('envisioneer scalable markets', 31.92, 3, '1964-06-15', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('reinvent sexy synergies', 32.51, 1, '1980-07-31', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('innovate next-generation e-tailers', 34.28, 5, '1837-09-10', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('revolutionize virtual action-items', 18.5, 4, '1901-07-13', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('disintermediate magnetic communities', 33.91, 3, '1991-12-29', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('transform front-end channels', 31.8, 1, '1922-06-17', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('incentivize bleeding-edge methodologies', 32.54, 2, '1991-01-04', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('synthesize 24/7 channels', 25.14, 4, '1954-06-03', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('revolutionize extensible deliverables', 20.91, 5, '1975-10-18', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('unleash frictionless synergies', 38.06, 2, '1862-11-22', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('benchmark extensible web-readiness', 22.64, 4, '1996-04-26', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('brand dot-com architectures', 26.54, 1, '1846-12-02', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('orchestrate dynamic models', 24.89, 5, '1898-05-24', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('transition world-class systems', 19.73, 1, '1876-03-30', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('synthesize turn-key portals', 39.6, 6, '1889-10-11', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('deploy next-generation infrastructures', 30.87, 1, '1911-04-04', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('generate rich models', 31.68, 1, '1983-08-09', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('scale proactive applications', 39.45, 3, '1879-04-29', 'EDM');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('integrate vertical architectures', 17.88, 3, '1893-11-25', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('engineer 24/365 e-services', 25.44, 4, '1909-05-23', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('productize innovative deliverables', 10.93, 3, '1944-04-10', 'Rhythm and Blues');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('expedite B2C experiences', 33.39, 5, '1972-05-19', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('facilitate viral relationships', 15.77, 1, '1920-10-28', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('integrate value-added architectures', 39.94, 4, '2004-02-29', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('deliver B2C relationships', 16.18, 5, '1893-10-25', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('engineer e-business niches', 15.17, 3, '1863-11-13', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('grow B2C bandwidth', 11.9, 1, '1931-12-30', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('whiteboard cutting-edge e-services', 35.31, 4, '1961-01-25', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('utilize enterprise vortals', 33.34, 2, '1924-02-16', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('scale best-of-breed infomediaries', 25.99, 1, '1975-07-26', 'Indie Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('harness rich bandwidth', 21.48, 1, '1969-03-01', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('grow dot-com networks', 36.18, 3, '1912-01-23', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('evolve sticky partnerships', 32.43, 1, '1840-02-25', 'Pop');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('leverage user-centric e-markets', 16.42, 3, '1957-04-25', 'EDM');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('benchmark web-enabled metrics', 26.44, 6, '2000-04-17', 'Electro');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('productize plug-and-play systems', 18.31, 2, '1919-11-09', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('brand vertical web services', 23.19, 4, '1981-03-26', 'Techno');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('engage collaborative ROI', 35.48, 5, '1983-02-01', 'EDM');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('aggregate global e-markets', 37.38, 1, '1858-02-13', 'Country');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('incubate cutting-edge vortals', 32.2, 3, '1964-01-04', 'Rock');
insert into Album (albumName, albumPrice, stockAmount, dateOfRelease, genre) values ('deploy sexy channels', 25.06, 2, '1928-01-30', 'Rhythm and Blues');
