insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Roxine', 'Ambrozewicz', 'Female', '1965-04-21', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Ryann', 'Tomaskunas', 'Female', '1994-08-20', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Noni', 'Huxtable', 'Female', '1985-12-25', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Janette', 'Tidball', 'Female', '1966-05-15', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Sherilyn', 'Shelf', 'Female', '1987-12-31', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Janel', 'Haugeh', 'Female', '1923-10-15', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Elaine', 'Ridde', 'Female', '1952-01-05', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Gar', 'Speck', 'Male', '1955-08-24', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hiram', 'Coffelt', 'Male', '1955-01-28', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Buddy', 'Etheridge', 'Male', '1937-08-09', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Edin', 'Chevin', 'Female', '1939-03-19', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Gabe', 'Butner', 'Male', '1971-10-08', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Artair', 'Hazleton', 'Male', '1924-06-19', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Veda', 'Loyd', 'Female', '1998-07-07', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Kippy', 'Hune', 'Male', '1929-02-24', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Tanner', 'Maddyson', 'Male', '1981-09-25', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hercules', 'Whichelow', 'Male', '2005-06-26', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Ulrick', 'Brenneke', 'Male', '1969-10-06', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Wallace', 'Oxlade', 'Male', '1976-06-05', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Charmain', 'Smout', 'Female', '1950-03-14', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Had', 'Tourot', 'Male', '1946-02-12', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Standford', 'Elger', 'Male', '1921-05-04', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Alaster', 'Crispin', 'Male', '1935-10-04', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Tremaine', 'Patroni', 'Male', '1999-05-16', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Whittaker', 'Peterken', 'Male', '1975-07-13', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Betti', 'Wavell', 'Female', '2006-04-20', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Dion', 'Everest', 'Male', '1965-10-14', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Ardis', 'Buy', 'Female', '1968-09-20', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Dahlia', 'Duignan', 'Female', '1950-07-29', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hobey', 'Roget', 'Male', '1943-01-24', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Jamie', 'Halfpenny', 'Female', '1973-10-07', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Marshall', 'Langmead', 'Male', '1998-05-22', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Chrisse', 'Flanagan', 'Male', '1923-05-15', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Gisele', 'Ahrens', 'Female', '1961-09-19', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Junie', 'Lesslie', 'Female', '1975-09-19', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Wendall', 'Goghin', 'Male', '1925-04-18', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Doti', 'Thew', 'Female', '1966-11-13', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Rodie', 'Stoodley', 'Female', '1959-04-27', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Malissia', 'Pauleau', 'Female', '1991-05-08', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Mayor', 'Gerkens', 'Male', '1927-11-29', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Jaye', 'Burrells', 'Male', '1938-08-16', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Shem', 'Cristofaro', 'Male', '1944-11-17', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Korney', 'Comford', 'Female', '1943-02-26', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Minetta', 'Coldridge', 'Female', '1961-07-09', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Emlyn', 'Terrill', 'Male', '1994-05-01', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Stormi', 'Didball', 'Female', '1980-10-24', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Cash', 'Escot', 'Male', '1984-11-18', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Stefa', 'Crosston', 'Female', '1967-08-04', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Wolfie', 'Musson', 'Male', '2004-08-06', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Lesley', 'Konrad', 'Female', '1978-05-07', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Elisha', 'Djurisic', 'Male', '1982-04-27', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Eloise', 'Louden', 'Female', '1963-02-19', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Violette', 'Schout', 'Female', '1922-10-15', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bronnie', 'Ezzy', 'Male', '1970-02-15', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Elga', 'Glass', 'Female', '1938-05-30', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Tulley', 'Kalkofer', 'Male', '1941-12-23', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Nicolai', 'Helm', 'Male', '1987-11-03', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Arabel', 'Castagne', 'Female', '1964-02-01', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Kris', 'Fakeley', 'Female', '1937-09-08', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Sasha', 'Corsor', 'Female', '1960-02-11', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Duane', 'Torricella', 'Male', '1996-01-26', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Julee', 'Oubridge', 'Female', '1984-02-11', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Aurelea', 'Grigolon', 'Female', '1993-03-28', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Harley', 'Amott', 'Female', '1989-07-29', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Koo', 'Lombard', 'Female', '1991-06-25', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Cece', 'Piff', 'Male', '1942-08-14', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Carry', 'Weatherell', 'Female', '1952-11-28', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Muriel', 'Selby', 'Female', '1984-10-28', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Stacey', 'Kuschel', 'Female', '1949-02-24', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Miguel', 'Lehr', 'Male', '1934-06-22', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Maribel', 'Bras', 'Female', '1933-08-06', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Ashia', 'Ondrusek', 'Female', '1962-03-14', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hollis', 'Janousek', 'Male', '1936-10-15', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Buffy', 'Cullington', 'Female', '1982-04-24', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bank', 'Webermann', 'Male', '1999-11-14', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Emmit', 'Artin', 'Male', '1921-03-11', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Zared', 'Littledike', 'Male', '1941-03-31', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Martelle', 'Edmenson', 'Female', '2007-08-21', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Tome', 'Alliston', 'Male', '2001-08-30', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Lanny', 'Winspire', 'Male', '1943-12-05', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Graham', 'Poulney', 'Male', '2001-04-17', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bonnie', 'Badder', 'Female', '1926-10-18', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Boonie', 'Durrell', 'Male', '1928-02-17', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Corabel', 'Sabbatier', 'Female', '1986-01-21', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Otto', 'Sells', 'Male', '1991-09-27', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Lukas', 'Coffin', 'Male', '1928-05-15', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Constance', 'Paxeford', 'Female', '1922-04-30', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Charline', 'Babin', 'Female', '1922-05-23', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Munmro', 'Cowderay', 'Male', '1924-01-12', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Yoshiko', 'Spraggon', 'Female', '1945-11-26', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Pearla', 'Allerton', 'Female', '1963-07-10', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Louise', 'Jenks', 'Female', '1969-01-01', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Wilburt', 'Aslett', 'Male', '1946-04-05', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Marlene', 'Whitchurch', 'Female', '1987-10-07', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Aindrea', 'Billam', 'Female', '1938-08-18', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Philipa', 'Syvret', 'Female', '2000-11-22', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Derwin', 'Isaak', 'Male', '1992-10-29', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Pietro', 'Gounel', 'Male', '1962-01-08', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Pippa', 'Chatten', 'Female', '1967-09-17', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Raddy', 'Puttan', 'Male', '1952-12-28', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Anita', 'Lempertz', 'Female', '2002-12-09', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Wileen', 'Grouvel', 'Female', '1947-09-18', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Annadiane', 'Matysiak', 'Female', '1976-11-22', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Wilona', 'Weldrick', 'Female', '1983-11-09', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Patricio', 'Garmon', 'Male', '1988-03-06', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Dal', 'De Miranda', 'Male', '2005-04-01', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Doti', 'Scrane', 'Female', '1975-10-17', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Sebastiano', 'Dows', 'Male', '1951-04-14', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Roberto', 'Cotman', 'Male', '2006-12-24', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Selig', 'Reisin', 'Male', '1980-10-15', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Delinda', 'Jessard', 'Female', '1988-12-28', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Nydia', 'Ketchell', 'Female', '1974-07-19', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Thurstan', 'Faich', 'Male', '1952-11-06', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Venita', 'Sainz', 'Female', '1989-07-07', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Giana', 'Martlew', 'Female', '1998-12-23', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Rafaellle', 'Perett', 'Male', '1992-06-14', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Dorey', 'Machel', 'Female', '1943-02-08', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Winthrop', 'Dyke', 'Male', '1949-05-12', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Lisa', 'Eckh', 'Female', '1971-07-14', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Massimiliano', 'Simeons', 'Male', '1922-09-20', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Sally', 'Arpino', 'Female', '1938-12-27', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Huntlee', 'Howsam', 'Male', '1983-11-18', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Godard', 'Garrie', 'Male', '1987-10-04', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hugo', 'Staneland', 'Male', '1992-12-17', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Renaud', 'Ewart', 'Male', '1924-12-19', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Rodge', 'Bayns', 'Male', '1964-02-16', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Nichols', 'Rysdale', 'Male', '1972-02-11', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Brande', 'Bussey', 'Female', '1986-10-06', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Abel', 'Dack', 'Male', '1922-08-18', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Armin', 'Higgan', 'Male', '1977-07-17', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Kamilah', 'Gauson', 'Female', '1948-02-25', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Valery', 'Skeffington', 'Female', '1934-05-07', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Jamison', 'Campione', 'Male', '1990-12-24', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bruis', 'Daw', 'Male', '1930-08-17', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Dare', 'Mixer', 'Male', '1950-04-17', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Karrie', 'Firpi', 'Female', '1994-06-20', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bernard', 'Laidlaw', 'Male', '2000-11-07', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Addi', 'Faucett', 'Female', '1929-05-26', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Eyde', 'Coast', 'Female', '1940-06-11', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Holmes', 'Orsi', 'Male', '1945-07-29', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Normand', 'Hartfleet', 'Male', '1985-01-11', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Stavros', 'Slavin', 'Male', '1986-06-13', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Caprice', 'Sibery', 'Female', '1956-05-26', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Shelbi', 'Glaysher', 'Female', '2000-06-03', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Desirae', 'Kepe', 'Female', '1950-01-04', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Otha', 'Richardes', 'Female', '1926-05-07', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Drake', 'Lince', 'Male', '1970-11-25', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Holly', 'McKinnon', 'Male', '1944-10-24', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Dot', 'Revel', 'Female', '2000-02-20', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Paolina', 'Bickerdike', 'Female', '1975-09-03', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Veda', 'MacUchadair', 'Female', '1996-05-04', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Edwina', 'Mallinder', 'Female', '1982-04-07', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Emmott', 'Skace', 'Male', '1921-04-15', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Zeke', 'Fass', 'Male', '1953-12-26', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Jordan', 'Boat', 'Female', '2001-09-05', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Tadd', 'Chyuerton', 'Male', '1959-12-05', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Min', 'Govinlock', 'Female', '1993-07-12', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Carlen', 'Padberry', 'Female', '1969-06-26', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Maggy', 'Tremeer', 'Female', '1948-01-10', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Alene', 'Babidge', 'Female', '1996-11-09', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Shaylynn', 'Blackstone', 'Female', '1981-11-26', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Alma', 'Learmont', 'Female', '1923-02-18', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Mabel', 'Volant', 'Female', '1944-08-18', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Reta', 'Chong', 'Female', '1960-05-10', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Georgie', 'Verrico', 'Male', '1947-12-13', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Crysta', 'Lenden', 'Female', '1955-06-02', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Llywellyn', 'Hall', 'Male', '1991-08-04', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bartholemy', 'Dauncey', 'Male', '1994-10-16', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hercule', 'Dendle', 'Male', '1945-02-10', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Timothea', 'Ebbotts', 'Female', '1976-08-16', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Heddie', 'Besson', 'Female', '1946-10-17', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Stephie', 'Skelbeck', 'Female', '1926-07-25', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Dedie', 'Ayree', 'Female', '1968-11-29', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Constantine', 'Boggish', 'Female', '1993-02-09', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Beltran', 'Yeliashev', 'Male', '1961-04-03', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Maddy', 'Kellard', 'Male', '1978-04-21', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Sigismondo', 'Aizikov', 'Male', '1988-05-14', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Patrick', 'Turbard', 'Male', '1961-07-12', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bennie', 'Brehaut', 'Female', '2007-05-28', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Chickie', 'Garth', 'Male', '2006-01-07', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Corina', 'Wimpeney', 'Female', '1949-10-25', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Andriana', 'Leafe', 'Female', '2004-10-21', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Marjorie', 'Ghidoni', 'Female', '1935-02-27', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Odella', 'Hazelhurst', 'Female', '1974-04-11', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Delano', 'Iacovides', 'Male', '1950-12-08', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Adelheid', 'Heikkinen', 'Female', '1927-08-30', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Archibald', 'Davers', 'Male', '1942-05-11', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('James', 'Dionsetti', 'Male', '1922-05-27', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Reggie', 'Arlett', 'Male', '1927-01-29', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Devora', 'Onion', 'Female', '1952-02-02', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Kippar', 'Fritter', 'Male', '1976-12-11', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bobina', 'Canada', 'Female', '1996-04-11', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bailey', 'Carnihan', 'Male', '1939-07-22', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Ringo', 'Cunde', 'Male', '1936-04-29', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Karlotta', 'Wolfarth', 'Female', '1991-10-19', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Bartolomeo', 'Bewsey', 'Male', '1922-08-28', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Isaak', 'Troake', 'Male', '1973-03-26', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Leicester', 'Ferbrache', 'Male', '1990-12-17', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Marina', 'Giacubo', 'Female', '1988-11-21', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Ethelbert', 'Pendrigh', 'Male', '1944-12-30', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Kenyon', 'Pauwel', 'Male', '1939-11-03', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Marleen', 'Manley', 'Female', '1921-08-29', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Clywd', 'Medina', 'Male', '1991-01-17', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Josiah', 'Ogan', 'Male', '1940-09-03', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Brennen', 'Oxley', 'Male', '1983-02-09', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Angele', 'Fewless', 'Female', '1922-12-12', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Val', 'Brooksbie', 'Female', '1981-07-25', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Emlen', 'Napolitano', 'Male', '1992-06-18', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Barb', 'McClaren', 'Female', '1934-08-21', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Nappy', 'Crumbleholme', 'Male', '1922-05-19', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hershel', 'MacGillespie', 'Male', '1930-05-17', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Jerrie', 'Unstead', 'Female', '1934-04-07', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Consalve', 'Mardell', 'Male', '1970-06-09', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Devlin', 'Jandak', 'Male', '1944-01-23', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Vick', 'Dalgetty', 'Male', '1984-09-30', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Kippar', 'Klimushev', 'Male', '1980-01-26', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Helenelizabeth', 'Dentith', 'Female', '1998-11-07', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Spenser', 'Brodbin', 'Male', '1923-06-11', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Salmon', 'Casswell', 'Male', '1979-05-20', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Kaila', 'Scowcraft', 'Female', '1977-03-20', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Gasper', 'Matus', 'Male', '1993-02-07', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Florenza', 'Legh', 'Female', '1976-12-27', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Ange', 'Muggeridge', 'Male', '1939-02-08', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Angeli', 'Veelers', 'Male', '1981-10-20', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Rebbecca', 'Furzer', 'Female', '2004-05-16', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Biron', 'Dobbyn', 'Male', '1934-05-17', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Ronny', 'Ianetti', 'Male', '1955-03-27', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Adamo', 'Espadater', 'Male', '2007-08-08', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('May', 'Mergue', 'Female', '1989-08-26', 'island Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Mathian', 'Beavan', 'Male', '1925-03-09', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Jobey', 'Blunt', 'Female', '2004-02-22', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Melanie', 'Gater', 'Female', '1939-11-12', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Finley', 'Casero', 'Male', '2000-01-06', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Brendan', 'Lathbury', 'Male', '1968-07-26', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Paige', 'Blunsden', 'Male', '1990-04-28', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Trevor', 'Burland', 'Male', '1938-01-27', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Gunther', 'Kelsell', 'Male', '1930-04-21', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Candis', 'Chatburn', 'Female', '1984-08-29', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Perrine', 'Domel', 'Female', '1994-07-11', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Wren', 'Nowakowska', 'Female', '2003-02-02', 'Def lam Recordings');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Lavina', 'Klammt', 'Female', '1974-08-20', 'Warner Music Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Arthur', 'Beilby', 'Male', '1935-07-09', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Aguste', 'Leatherbarrow', 'Male', '2003-06-11', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Petr', 'Crippell', 'Male', '1970-11-02', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Trescha', 'Minette', 'Female', '1944-04-22', 'Red Hill Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Jeffie', 'Scotter', 'Male', '1958-01-05', 'Universal Music Publishing Group');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Berthe', 'Strotone', 'Female', '1986-03-03', 'Atlantic Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hermann', 'Georgeot', 'Male', '1961-06-07', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Hazel', 'Wevell', 'Male', '1947-11-17', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Tammy', 'Beddow', 'Male', '1993-04-30', 'BMG Rights Management');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Katina', 'Goomes', 'Female', '1986-10-01', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Annadiana', 'Rojas', 'Female', '1930-03-11', 'ABC-Paramount Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Stern', 'Kleehuhler', 'Male', '1932-02-17', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Karel', 'Biasi', 'Male', '1958-03-25', 'virgin Records');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Justin', 'Stivani', 'Male', '1994-06-19', 'Sony Music Entertainment');
insert into Artist (firstName, lastName, gender, dateOfBirth, recordLabel) values ('Rachael', 'Yakovl', 'Female', '2003-09-02', 'virgin Records');
