insert into recordcompany values ("ABC-Paramount Records", "ABC Records happened to be the most talked about music label operated by Am-Par Record Corporation.");
insert into recordcompany values ("Atlantic Records", "Earning a reputation to have specialized in R&B, Jazz and soul recordings, Atlantic Records was founded in 1947.");
insert into recordcompany values ("BMG Rights Management","Established in 2008 BMG may be the youngest international music company.");
insert into recordcompany values ("Def lam Recordings","Owned by the Universal Music Group, the record label primarily focuses on urban and hip-hop music.");
insert into recordcompany values ("island Records","Founded in 1959. Island Records is a division of the Universal Music Group that has been a platform for several of the world's most favorite artists.");
insert into recordcompany values ("Red Hill Records","Red Hill Records is a segment of the independent Christian record label, Pamplin Music, which was founded in 1995.");
insert into recordcompany values ("Sony Music Entertainment","Sony Music company was founded in 1929 by the name American Record Corporation. Headquartered in New York City.");
insert into recordcompany values ("Universal Music Publishing Group","The world's second largest music publishing company after Sony/AN Music Publishing. Headquarters in Santa Monica. California.");
insert into recordcompany values ("virgin Records","Virgin Records was founded in 1972 by entrepreneurs Richard Branson, Nik Powell, Tom Newman and Simon Draper. Headquarters in Los Angeles, Calafornia.");
insert into recordcompany values ("Warner Music Group","Headquartered in New York City, this American multinational entertainment conglomerate stands third in the music industry.");