insert into Track (catalogueNo, trackName, trackLength) values (6, 'Campylopus Moss', 4.25);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Larch Dwarf Mistletoe', 5.22);
insert into Track (catalogueNo, trackName, trackLength) values (73, 'Beautiful Bladderpod', 3.24);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Purple Avens', 5.03);
insert into Track (catalogueNo, trackName, trackLength) values (57, 'Texas Ash', 2.43);
insert into Track (catalogueNo, trackName, trackLength) values (119, 'Silverleaf Phacelia', 5.13);
insert into Track (catalogueNo, trackName, trackLength) values (50, 'Pyrenidium Lichen', 4.11);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Cusp Dodder', 1.52);
insert into Track (catalogueNo, trackName, trackLength) values (63, 'London Planetree', 2.54);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Hybrid Hawthorn', 5.17);
insert into Track (catalogueNo, trackName, trackLength) values (129, 'Eared Coneflower', 3.38);
insert into Track (catalogueNo, trackName, trackLength) values (65, 'Zahlbruckner''s Peltula Lichen', 2.59);
insert into Track (catalogueNo, trackName, trackLength) values (49, 'Longspur Lupine', 1.53);
insert into Track (catalogueNo, trackName, trackLength) values (6, 'Johnny-nip', 5.09);
insert into Track (catalogueNo, trackName, trackLength) values (83, 'Streamside Orthotrichum Moss', 3.02);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Spring Hill Flax', 2.11);
insert into Track (catalogueNo, trackName, trackLength) values (40, '''ohi''a Lehua', 1.36);
insert into Track (catalogueNo, trackName, trackLength) values (39, 'Map Lichen', 3.01);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Dwarf Rose', 1.42);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Scarlet Bottlebrush', 3.33);
insert into Track (catalogueNo, trackName, trackLength) values (45, 'Tobacco Root', 2.53);
insert into Track (catalogueNo, trackName, trackLength) values (122, 'Rabbitsfoot Grass', 4.27);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Tropical Passionflower', 1.43);
insert into Track (catalogueNo, trackName, trackLength) values (37, 'Threadleaf Fleabane', 2.3);
insert into Track (catalogueNo, trackName, trackLength) values (91, 'West Indian Cock''s Comb', 2.56);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Dwarf Mentzelia', 2.29);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Ashe''s Magnolia', 3.06);
insert into Track (catalogueNo, trackName, trackLength) values (42, 'Bryum Moss', 5.44);
insert into Track (catalogueNo, trackName, trackLength) values (133, 'Goldfields', 1.49);
insert into Track (catalogueNo, trackName, trackLength) values (11, 'Reverchon''s Palafox', 3.1);
insert into Track (catalogueNo, trackName, trackLength) values (1, 'Folded Calicoflower', 4.43);
insert into Track (catalogueNo, trackName, trackLength) values (118, 'Awnless Beardgrass', 5.18);
insert into Track (catalogueNo, trackName, trackLength) values (38, 'Sedge', 2.4);
insert into Track (catalogueNo, trackName, trackLength) values (42, 'Meager Pygmydaisy', 4.01);
insert into Track (catalogueNo, trackName, trackLength) values (7, 'Yerba De Guava', 3.55);
insert into Track (catalogueNo, trackName, trackLength) values (71, 'Lecidea Lichen', 3.05);
insert into Track (catalogueNo, trackName, trackLength) values (113, 'Labrador Cup Lichen', 3.33);
insert into Track (catalogueNo, trackName, trackLength) values (10, 'Hawai''i Ticktrefoil', 5.39);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Sieber''s Filmy Fern', 5.07);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Hemlock Rosette Grass', 3.45);
insert into Track (catalogueNo, trackName, trackLength) values (19, 'Ruth''s Sedge', 2.48);
insert into Track (catalogueNo, trackName, trackLength) values (118, 'Brackenridge''s Rosemallow', 5.17);
insert into Track (catalogueNo, trackName, trackLength) values (46, 'Common Twinpod', 4.31);
insert into Track (catalogueNo, trackName, trackLength) values (52, 'Risdon Peppermint Gum', 1.53);
insert into Track (catalogueNo, trackName, trackLength) values (124, 'Bald Bedstraw', 4.15);
insert into Track (catalogueNo, trackName, trackLength) values (63, 'Eastwood''s Baby Blue Eyes', 4.14);
insert into Track (catalogueNo, trackName, trackLength) values (104, 'Bahama Maidenbush', 3.45);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'Cardenala Azul', 1.34);
insert into Track (catalogueNo, trackName, trackLength) values (64, 'Cory''s Croton', 1.32);
insert into Track (catalogueNo, trackName, trackLength) values (4, 'Parry''s Clover', 5.37);
insert into Track (catalogueNo, trackName, trackLength) values (122, 'Desert Twinbugs', 2.1);
insert into Track (catalogueNo, trackName, trackLength) values (99, 'Carolina Horsenettle', 5.42);
insert into Track (catalogueNo, trackName, trackLength) values (97, 'Sneezeweed', 2.15);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Psorula Lichen', 2.1);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Lindheimer''s Hogwort', 1.54);
insert into Track (catalogueNo, trackName, trackLength) values (132, 'Pitcherplant', 4.51);
insert into Track (catalogueNo, trackName, trackLength) values (71, 'Perez''s Sea Lavender', 4.23);
insert into Track (catalogueNo, trackName, trackLength) values (126, 'Allantoparmelia Lichen', 5.13);
insert into Track (catalogueNo, trackName, trackLength) values (61, 'False Sunflower', 2.1);
insert into Track (catalogueNo, trackName, trackLength) values (116, 'Fivepetal Leaf-flower', 5.24);
insert into Track (catalogueNo, trackName, trackLength) values (108, 'Perforated Parmotrema Lichen', 1.56);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Elephantsfoot', 2.55);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Dwarf-primrose', 5.28);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'Canadian Summer Bluet', 2.23);
insert into Track (catalogueNo, trackName, trackLength) values (67, 'Sclerophora Lichen', 3.13);
insert into Track (catalogueNo, trackName, trackLength) values (39, 'Naked Buckwheat', 5.01);
insert into Track (catalogueNo, trackName, trackLength) values (34, 'Wickerstem Buckwheat', 4.17);
insert into Track (catalogueNo, trackName, trackLength) values (89, 'Robin Redbreast Bush', 2.19);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Fendler''s Sandwort', 2.42);
insert into Track (catalogueNo, trackName, trackLength) values (5, 'Sierra Shootingstar', 1.35);
insert into Track (catalogueNo, trackName, trackLength) values (50, 'Ballhead Ipomopsis', 2.23);
insert into Track (catalogueNo, trackName, trackLength) values (10, 'Rock Violet', 2.14);
insert into Track (catalogueNo, trackName, trackLength) values (14, 'Kokee Yellow Loosestrife', 2.17);
insert into Track (catalogueNo, trackName, trackLength) values (15, 'Sudan Raphia Palm', 4.01);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Wright''s Thelypody', 1.57);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Pteroglossaspis', 3.05);
insert into Track (catalogueNo, trackName, trackLength) values (132, 'Watson''s Spikemoss', 3.49);
insert into Track (catalogueNo, trackName, trackLength) values (2, 'Hoary Brome', 4.26);
insert into Track (catalogueNo, trackName, trackLength) values (91, 'Spiked Spiralflag', 4.3);
insert into Track (catalogueNo, trackName, trackLength) values (119, 'Clebsch''s Fissidens Moss', 2.17);
insert into Track (catalogueNo, trackName, trackLength) values (82, 'Manzanita', 3.31);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Jacobi''s Schiedea', 4.52);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Texas Rim Lichen', 4.45);
insert into Track (catalogueNo, trackName, trackLength) values (11, 'Carolina Wild Petunia', 2.12);
insert into Track (catalogueNo, trackName, trackLength) values (34, 'Wiry Panicgrass', 4);
insert into Track (catalogueNo, trackName, trackLength) values (98, 'Sweetclover Vetch', 5.3);
insert into Track (catalogueNo, trackName, trackLength) values (90, 'Lombardy Poplar', 1.59);
insert into Track (catalogueNo, trackName, trackLength) values (70, 'Sarita Rosette Grass', 3.15);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Harrison''s Stickseed', 3.13);
insert into Track (catalogueNo, trackName, trackLength) values (120, 'Bog Rosette Grass', 2.56);
insert into Track (catalogueNo, trackName, trackLength) values (121, 'Butte County Fritillary', 2.44);
insert into Track (catalogueNo, trackName, trackLength) values (40, 'Greater Yellowthroat Gilia', 2.2);
insert into Track (catalogueNo, trackName, trackLength) values (90, 'Pygmy Clover', 4.03);
insert into Track (catalogueNo, trackName, trackLength) values (39, 'Whitecolumn Foxtail Cactus', 4.4);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Wind River Rockcress', 3.5);
insert into Track (catalogueNo, trackName, trackLength) values (128, 'Chiricahua Mountain Stinkweed', 3.52);
insert into Track (catalogueNo, trackName, trackLength) values (102, 'Ptychosperma', 2.01);
insert into Track (catalogueNo, trackName, trackLength) values (91, 'Turgid Cup Lichen', 2.23);
insert into Track (catalogueNo, trackName, trackLength) values (107, 'Globemallow', 3.01);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Creosote Bush', 2.1);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'Panoche Pepperweed', 4.5);
insert into Track (catalogueNo, trackName, trackLength) values (20, 'Javanese Long Pepper', 2.31);
insert into Track (catalogueNo, trackName, trackLength) values (18, 'Wavy Heliotrope', 1.43);
insert into Track (catalogueNo, trackName, trackLength) values (75, 'Isachne', 3.34);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Turpinia', 1.56);
insert into Track (catalogueNo, trackName, trackLength) values (58, 'Marked Woollystar', 4.15);
insert into Track (catalogueNo, trackName, trackLength) values (105, 'Shortspur Seablush', 4.08);
insert into Track (catalogueNo, trackName, trackLength) values (78, 'Common Threesquare', 3.33);
insert into Track (catalogueNo, trackName, trackLength) values (43, 'Vavilov''s Wheat', 4.51);
insert into Track (catalogueNo, trackName, trackLength) values (39, 'Western Columbine', 4.56);
insert into Track (catalogueNo, trackName, trackLength) values (38, 'Shaggy Lupine', 4.32);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Cannonball Tree', 5.1);
insert into Track (catalogueNo, trackName, trackLength) values (121, 'Glandleaf Prairie Clover', 2.43);
insert into Track (catalogueNo, trackName, trackLength) values (1, 'Veldt-grape', 2.54);
insert into Track (catalogueNo, trackName, trackLength) values (103, 'Lentil', 5.24);
insert into Track (catalogueNo, trackName, trackLength) values (78, 'Mexican Orange', 5.16);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Masai Clover', 1.59);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'Wholeleaf Rosinweed', 3.59);
insert into Track (catalogueNo, trackName, trackLength) values (49, 'Canadian Hawthorn', 2.1);
insert into Track (catalogueNo, trackName, trackLength) values (19, 'Smooth Fanpetals', 5.11);
insert into Track (catalogueNo, trackName, trackLength) values (109, 'Streamside Map Lichen', 1.42);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Seneca Snakeroot', 1.54);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'Tuffybells', 3.39);
insert into Track (catalogueNo, trackName, trackLength) values (33, 'Yellow Pepperweed', 2.35);
insert into Track (catalogueNo, trackName, trackLength) values (122, 'Leonard''s Beardtongue', 4.15);
insert into Track (catalogueNo, trackName, trackLength) values (83, 'Burma Padauk', 3.01);
insert into Track (catalogueNo, trackName, trackLength) values (91, 'Sphagnum', 4.17);
insert into Track (catalogueNo, trackName, trackLength) values (98, 'Hairy Cyanea', 5.27);
insert into Track (catalogueNo, trackName, trackLength) values (78, 'Sulphur-flower Buckwheat', 4.41);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'Hediondilla', 4.23);
insert into Track (catalogueNo, trackName, trackLength) values (91, 'French-grass', 3.45);
insert into Track (catalogueNo, trackName, trackLength) values (12, 'Dot Lichen', 1.57);
insert into Track (catalogueNo, trackName, trackLength) values (30, 'Cochlospermum', 5.19);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Leucodon Moss', 3.23);
insert into Track (catalogueNo, trackName, trackLength) values (12, 'Nodding Sunray', 2.05);
insert into Track (catalogueNo, trackName, trackLength) values (52, 'Gregg''s Sensitive Pea', 2.09);
insert into Track (catalogueNo, trackName, trackLength) values (71, 'Taimyr Catchfly', 2.05);
insert into Track (catalogueNo, trackName, trackLength) values (58, 'Blueeyed Grass', 4.39);
insert into Track (catalogueNo, trackName, trackLength) values (82, 'Orange Lichen', 2.51);
insert into Track (catalogueNo, trackName, trackLength) values (85, 'Asian Bushbeech', 1.29);
insert into Track (catalogueNo, trackName, trackLength) values (36, 'Adequate Spike Lichen', 2.44);
insert into Track (catalogueNo, trackName, trackLength) values (12, 'Kern Plateau Bird''s-beak', 1.56);
insert into Track (catalogueNo, trackName, trackLength) values (1, 'Sonoran Bean', 5.35);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'West Indian Pinkroot', 3.13);
insert into Track (catalogueNo, trackName, trackLength) values (12, 'Dwarf Western Rosinweed', 4.16);
insert into Track (catalogueNo, trackName, trackLength) values (127, 'Drug Eyebright', 3.33);
insert into Track (catalogueNo, trackName, trackLength) values (116, 'Lemonyellow False Goldenaster', 3.49);
insert into Track (catalogueNo, trackName, trackLength) values (77, 'Pulvinate Schistidium Moss', 3.24);
insert into Track (catalogueNo, trackName, trackLength) values (81, 'Johnny-jump-up', 3.23);
insert into Track (catalogueNo, trackName, trackLength) values (38, 'Oakfern', 3.23);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Giant Deathcamas', 1.27);
insert into Track (catalogueNo, trackName, trackLength) values (2, 'Cows Clover', 5.36);
insert into Track (catalogueNo, trackName, trackLength) values (104, 'Grassleaf Barbara''s Buttons', 5.07);
insert into Track (catalogueNo, trackName, trackLength) values (119, 'White Alling', 5.05);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Sawtooth Sunflower', 1.52);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Grass Of Parnassus', 5.38);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Entireleaf Mountain-avens', 4.19);
insert into Track (catalogueNo, trackName, trackLength) values (129, 'Saltmarsh Bird''s-beak', 4.3);
insert into Track (catalogueNo, trackName, trackLength) values (46, 'White False Hellebore', 5.08);
insert into Track (catalogueNo, trackName, trackLength) values (63, 'Antillean Furcraea', 5.14);
insert into Track (catalogueNo, trackName, trackLength) values (38, 'Fringed Knotweed', 5.06);
insert into Track (catalogueNo, trackName, trackLength) values (98, 'Dwarf Polypody', 1.58);
insert into Track (catalogueNo, trackName, trackLength) values (123, 'Palmer''s Cornsalad', 5.31);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Cowhorn Orchid', 5);
insert into Track (catalogueNo, trackName, trackLength) values (113, 'Spearbract Blue-eyed Grass', 1.39);
insert into Track (catalogueNo, trackName, trackLength) values (86, 'Scrabrous Black Sedge', 3.47);
insert into Track (catalogueNo, trackName, trackLength) values (23, 'Gregg''s Keelpod', 2.44);
insert into Track (catalogueNo, trackName, trackLength) values (38, 'Silver Hairgrass', 3.09);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Croton', 2.25);
insert into Track (catalogueNo, trackName, trackLength) values (46, 'Copperleaf', 2.48);
insert into Track (catalogueNo, trackName, trackLength) values (133, 'Chocolate Vine', 5.36);
insert into Track (catalogueNo, trackName, trackLength) values (27, 'Strawberryleaf Cinquefoil', 5.44);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Slender Cinquefoil', 5.33);
insert into Track (catalogueNo, trackName, trackLength) values (41, 'Ashy Silktassel', 2.29);
insert into Track (catalogueNo, trackName, trackLength) values (15, 'Wild Crapemyrtle', 2.43);
insert into Track (catalogueNo, trackName, trackLength) values (33, 'Rough Desertparsley', 2.37);
insert into Track (catalogueNo, trackName, trackLength) values (33, 'Yellow Columbine', 3.59);
insert into Track (catalogueNo, trackName, trackLength) values (72, 'Sand Buckwheat', 5.01);
insert into Track (catalogueNo, trackName, trackLength) values (95, 'Graceful Pouzolzsbush', 2.42);
insert into Track (catalogueNo, trackName, trackLength) values (22, 'Pot Marjoram', 2.15);
insert into Track (catalogueNo, trackName, trackLength) values (40, 'Woolly Huckleberry', 5.37);
insert into Track (catalogueNo, trackName, trackLength) values (86, 'Striped Prince''s Pine', 4);
insert into Track (catalogueNo, trackName, trackLength) values (84, 'Cup Lichen', 4.29);
insert into Track (catalogueNo, trackName, trackLength) values (120, 'Hairy Schiedea', 1.41);
insert into Track (catalogueNo, trackName, trackLength) values (11, 'Bergamot Orange', 5.03);
insert into Track (catalogueNo, trackName, trackLength) values (34, 'Ashen Milkvetch', 2.27);
insert into Track (catalogueNo, trackName, trackLength) values (80, 'American Madwort', 4.2);
insert into Track (catalogueNo, trackName, trackLength) values (36, 'Metcalf Canyon Jewelflower', 1.24);
insert into Track (catalogueNo, trackName, trackLength) values (117, 'Heckard''s Indian Paintbrush', 5.14);
insert into Track (catalogueNo, trackName, trackLength) values (44, 'Virginia Fanpetals', 2.47);
insert into Track (catalogueNo, trackName, trackLength) values (3, 'Woodland Calamint', 2.25);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Wartremoving Herb', 1.43);
insert into Track (catalogueNo, trackName, trackLength) values (1, 'Freckled Milkvetch', 3.06);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Parasitic Maiden Fern', 2.32);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Bartlettia', 4.05);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'Perfoliate Blackfoot', 3.41);
insert into Track (catalogueNo, trackName, trackLength) values (9, 'Caribbean Mayten', 5.44);
insert into Track (catalogueNo, trackName, trackLength) values (128, 'Foxglove', 1.45);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Western Sunflower', 4.2);
insert into Track (catalogueNo, trackName, trackLength) values (21, 'Whipple Cholla', 4.38);
insert into Track (catalogueNo, trackName, trackLength) values (55, 'California Yerba Santa', 2.37);
insert into Track (catalogueNo, trackName, trackLength) values (71, 'Makaleha Maiden Fern', 3.28);
insert into Track (catalogueNo, trackName, trackLength) values (57, 'Mouseear Hawkweed', 4.08);
insert into Track (catalogueNo, trackName, trackLength) values (78, 'Rubber Rabbitbrush', 2.26);
insert into Track (catalogueNo, trackName, trackLength) values (103, 'Shrubby Bedstraw', 1.25);
insert into Track (catalogueNo, trackName, trackLength) values (77, 'Common Mediterranean Grass', 5.29);
insert into Track (catalogueNo, trackName, trackLength) values (64, 'Island Redberry', 3.41);
insert into Track (catalogueNo, trackName, trackLength) values (114, 'Smallflower Fishhook Cactus', 4.55);
insert into Track (catalogueNo, trackName, trackLength) values (128, 'Spreading Thelypodiopsis', 2.58);
insert into Track (catalogueNo, trackName, trackLength) values (84, 'Crater Lichen', 4.12);
insert into Track (catalogueNo, trackName, trackLength) values (7, 'Canadian Horseweed', 4.32);
insert into Track (catalogueNo, trackName, trackLength) values (50, 'Wedgeleaf Draba', 4.53);
insert into Track (catalogueNo, trackName, trackLength) values (79, 'Beet', 5.38);
insert into Track (catalogueNo, trackName, trackLength) values (128, 'Paperbark-thorn', 2.1);
insert into Track (catalogueNo, trackName, trackLength) values (75, 'Fourpart Dwarf Gentian', 5.04);
insert into Track (catalogueNo, trackName, trackLength) values (127, 'Kaibab Bird''s Beak', 4.36);
insert into Track (catalogueNo, trackName, trackLength) values (43, 'Common Calabash Tree', 4.23);
insert into Track (catalogueNo, trackName, trackLength) values (15, 'Purple Milkweed', 2.34);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Dot Lichen', 2.46);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Longhorn Steer''s-head', 3.28);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Sedge', 5.02);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Graphina Lichen', 3.4);
insert into Track (catalogueNo, trackName, trackLength) values (61, 'Lemmon''s Rockcress', 5.09);
insert into Track (catalogueNo, trackName, trackLength) values (30, 'Cultivated Raspberry', 3.06);
insert into Track (catalogueNo, trackName, trackLength) values (78, 'Yellow Pond-lily', 1.43);
insert into Track (catalogueNo, trackName, trackLength) values (122, 'Greene''s Bird''s-foot Trefoil', 4.46);
insert into Track (catalogueNo, trackName, trackLength) values (49, 'Barrier Range Wattle', 2.28);
insert into Track (catalogueNo, trackName, trackLength) values (97, 'Richardson''s Brookfoam', 3.44);
insert into Track (catalogueNo, trackName, trackLength) values (108, 'Sierra Fringed Gentian', 3.35);
insert into Track (catalogueNo, trackName, trackLength) values (114, 'Guarana', 2.58);
insert into Track (catalogueNo, trackName, trackLength) values (89, 'Quickstick', 4.2);
insert into Track (catalogueNo, trackName, trackLength) values (89, 'Bearded Sprangletop', 1.44);
insert into Track (catalogueNo, trackName, trackLength) values (65, 'Payson''s Bladderpod', 4.44);
insert into Track (catalogueNo, trackName, trackLength) values (91, 'Hentz''s Phlox', 2.23);
insert into Track (catalogueNo, trackName, trackLength) values (111, 'Pyrenopsis Lichen', 4.15);
insert into Track (catalogueNo, trackName, trackLength) values (21, 'Mickey Mouse Plant', 2.41);
insert into Track (catalogueNo, trackName, trackLength) values (120, 'Davidson''s Penstemon', 3.59);
insert into Track (catalogueNo, trackName, trackLength) values (103, 'San Diego Wild Cabbage', 2.35);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Sierra Lupine', 4.16);
insert into Track (catalogueNo, trackName, trackLength) values (84, 'Cooper''s Lipfern', 1.49);
insert into Track (catalogueNo, trackName, trackLength) values (43, 'Geyer''s Sandmat', 2.15);
insert into Track (catalogueNo, trackName, trackLength) values (55, 'Virginia Pinweed', 4.3);
insert into Track (catalogueNo, trackName, trackLength) values (95, 'Bupleurum', 4.56);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Octoblepharum Moss', 4.4);
insert into Track (catalogueNo, trackName, trackLength) values (98, 'Dusty Miller', 4.04);
insert into Track (catalogueNo, trackName, trackLength) values (89, 'Sea Kale', 5.38);
insert into Track (catalogueNo, trackName, trackLength) values (34, 'Mogollon Lousewort', 4.07);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Cabellos De Angel', 1.37);
insert into Track (catalogueNo, trackName, trackLength) values (46, 'Donn''s Small Limestone Moss', 3.41);
insert into Track (catalogueNo, trackName, trackLength) values (47, 'Belladonna Lily', 4.54);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'Gunnera', 4.25);
insert into Track (catalogueNo, trackName, trackLength) values (54, 'Dotted Lichen', 5.12);
insert into Track (catalogueNo, trackName, trackLength) values (54, 'Rock Willow', 3.57);
insert into Track (catalogueNo, trackName, trackLength) values (95, 'Cutleaf Bur Cucumber', 1.3);
insert into Track (catalogueNo, trackName, trackLength) values (67, 'Stonecrop Phacelia', 5.32);
insert into Track (catalogueNo, trackName, trackLength) values (68, 'Lion''s Tail', 1.39);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'Serpentine Draba', 3.33);
insert into Track (catalogueNo, trackName, trackLength) values (2, 'Blue Ridge Shield Lichen', 3.25);
insert into Track (catalogueNo, trackName, trackLength) values (95, 'Littleflower Alumroot', 4.04);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Poison Ash', 2.35);
insert into Track (catalogueNo, trackName, trackLength) values (54, 'Burrweed', 2.32);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Caliche Globemallow', 3.54);
insert into Track (catalogueNo, trackName, trackLength) values (73, 'Echinoplaca Lichen', 3.44);
insert into Track (catalogueNo, trackName, trackLength) values (124, 'Thread Lichen', 5.02);
insert into Track (catalogueNo, trackName, trackLength) values (47, 'Sierra Gooseberry', 3.29);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Russelia', 1.46);
insert into Track (catalogueNo, trackName, trackLength) values (3, 'Epiphytic Flatsedge', 4.35);
insert into Track (catalogueNo, trackName, trackLength) values (105, 'Oahu Sedge', 4.38);
insert into Track (catalogueNo, trackName, trackLength) values (7, 'Leucobryum Moss', 3.03);
insert into Track (catalogueNo, trackName, trackLength) values (9, 'Quill Spikerush', 2.22);
insert into Track (catalogueNo, trackName, trackLength) values (26, 'Adderstongue', 4.41);
insert into Track (catalogueNo, trackName, trackLength) values (66, 'Chalice Lichen', 4.38);
insert into Track (catalogueNo, trackName, trackLength) values (132, 'Tidalmarsh Amaranth', 2.51);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'Floatingheart', 5);
insert into Track (catalogueNo, trackName, trackLength) values (9, 'Cape Blue Waterlily', 5.04);
insert into Track (catalogueNo, trackName, trackLength) values (105, 'Rim Lichen', 2.39);
insert into Track (catalogueNo, trackName, trackLength) values (75, 'Andalusian Pohlia Moss', 4.5);
insert into Track (catalogueNo, trackName, trackLength) values (54, 'Octopus Fern', 3.53);
insert into Track (catalogueNo, trackName, trackLength) values (18, 'Aberdeen Dewberry', 1.5);
insert into Track (catalogueNo, trackName, trackLength) values (46, 'Angiopteris Fern', 1.47);
insert into Track (catalogueNo, trackName, trackLength) values (81, 'Chilean Chess', 2.46);
insert into Track (catalogueNo, trackName, trackLength) values (52, 'Sweet Osmanthus', 4.08);
insert into Track (catalogueNo, trackName, trackLength) values (9, 'Hybrid Oak', 5.15);
insert into Track (catalogueNo, trackName, trackLength) values (86, 'Schinopsis', 5.23);
insert into Track (catalogueNo, trackName, trackLength) values (93, 'Mat Penstemon', 3.2);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Pepper', 3.55);
insert into Track (catalogueNo, trackName, trackLength) values (3, 'Lecidea Lichen', 5.35);
insert into Track (catalogueNo, trackName, trackLength) values (122, 'Red Fescue', 3.09);
insert into Track (catalogueNo, trackName, trackLength) values (19, 'Mung Bean', 5.17);
insert into Track (catalogueNo, trackName, trackLength) values (90, 'Kentucky Lady''s Slipper', 1.3);
insert into Track (catalogueNo, trackName, trackLength) values (114, 'Woolly Milkweed', 1.5);
insert into Track (catalogueNo, trackName, trackLength) values (14, 'European Fan Palm', 4.5);
insert into Track (catalogueNo, trackName, trackLength) values (107, 'Peltula Lichen', 2.31);
insert into Track (catalogueNo, trackName, trackLength) values (86, 'Ragwort', 4);
insert into Track (catalogueNo, trackName, trackLength) values (129, 'Mojave Cottonthorn', 2.17);
insert into Track (catalogueNo, trackName, trackLength) values (33, 'Common Rush', 2.4);
insert into Track (catalogueNo, trackName, trackLength) values (5, 'Death Valley Monkeyflower', 1.35);
insert into Track (catalogueNo, trackName, trackLength) values (94, 'Nodding Locoweed', 4.42);
insert into Track (catalogueNo, trackName, trackLength) values (21, 'Spoonleaf Yellow Loosestrife', 3.06);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Fabronia Moss', 2.35);
insert into Track (catalogueNo, trackName, trackLength) values (28, 'Cup Lichen', 2.16);
insert into Track (catalogueNo, trackName, trackLength) values (129, 'Brunswickgrass', 5.41);
insert into Track (catalogueNo, trackName, trackLength) values (79, 'Carolina Larkspur', 1.45);
insert into Track (catalogueNo, trackName, trackLength) values (9, 'Navajo Bladderpod', 3.04);
insert into Track (catalogueNo, trackName, trackLength) values (19, 'Cape-ivy', 1.38);
insert into Track (catalogueNo, trackName, trackLength) values (2, 'Shortleaf Baccharis', 1.37);
insert into Track (catalogueNo, trackName, trackLength) values (134, 'Nootka Lupine', 1.39);
insert into Track (catalogueNo, trackName, trackLength) values (54, 'Combleaf Yellow False Foxglove', 5.42);
insert into Track (catalogueNo, trackName, trackLength) values (44, 'Coastal Manroot', 4.28);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Tortella Moss', 4.37);
insert into Track (catalogueNo, trackName, trackLength) values (15, 'Hirsute Sedge', 5.23);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Rhytidiopsis Moss', 2.02);
insert into Track (catalogueNo, trackName, trackLength) values (102, 'Hybrid Hickory', 1.51);
insert into Track (catalogueNo, trackName, trackLength) values (52, 'Drew''s Silky Lupine', 2.15);
insert into Track (catalogueNo, trackName, trackLength) values (94, 'Hoffmannsegg''s Wild Coffee', 1.57);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Rim Lichen', 1.24);
insert into Track (catalogueNo, trackName, trackLength) values (111, 'Copey Vera', 1.24);
insert into Track (catalogueNo, trackName, trackLength) values (19, 'Nevada Buckthorn', 3.11);
insert into Track (catalogueNo, trackName, trackLength) values (54, 'Splitbeard Bluestem', 4.58);
insert into Track (catalogueNo, trackName, trackLength) values (85, 'Rusby''s Flatsedge', 4.35);
insert into Track (catalogueNo, trackName, trackLength) values (93, 'Rinodina Lichen', 3.39);
insert into Track (catalogueNo, trackName, trackLength) values (63, 'Calicoflower', 1.42);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Kio''ele', 5.36);
insert into Track (catalogueNo, trackName, trackLength) values (130, 'Fendler''s Sandwort', 1.52);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Thrombium Lichen', 5.21);
insert into Track (catalogueNo, trackName, trackLength) values (133, 'English Bluebell', 2.19);
insert into Track (catalogueNo, trackName, trackLength) values (69, 'Common Dandelion', 5.12);
insert into Track (catalogueNo, trackName, trackLength) values (86, 'Hybrid Rose', 3.13);
insert into Track (catalogueNo, trackName, trackLength) values (124, 'Rose Linanthus', 5.31);
insert into Track (catalogueNo, trackName, trackLength) values (102, 'Longleaf Phlox', 5.05);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Broom-like Ragwort', 2.33);
insert into Track (catalogueNo, trackName, trackLength) values (88, 'Koholapehu', 5.2);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Carey''s Balsamroot', 2.03);
insert into Track (catalogueNo, trackName, trackLength) values (5, 'Harvestlice', 4.11);
insert into Track (catalogueNo, trackName, trackLength) values (104, 'Stiff Greenthread', 3.13);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Rim Lichen', 4.57);
insert into Track (catalogueNo, trackName, trackLength) values (122, 'Sitka Rockbrake', 2.17);
insert into Track (catalogueNo, trackName, trackLength) values (93, 'Bushy Bluestem', 5.19);
insert into Track (catalogueNo, trackName, trackLength) values (129, 'Tricharia Lichen', 4.42);
insert into Track (catalogueNo, trackName, trackLength) values (56, 'Scottish Licorice-root', 2.4);
insert into Track (catalogueNo, trackName, trackLength) values (2, 'Kern County Milkvetch', 5.38);
insert into Track (catalogueNo, trackName, trackLength) values (97, 'Sobralia', 2.45);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'False Melic', 3.46);
insert into Track (catalogueNo, trackName, trackLength) values (65, 'Japanese Yew', 2.19);
insert into Track (catalogueNo, trackName, trackLength) values (131, 'Cheiridopsis', 2.35);
insert into Track (catalogueNo, trackName, trackLength) values (39, 'Graphina Lichen', 4.03);
insert into Track (catalogueNo, trackName, trackLength) values (119, 'Chenille Honeymyrtle', 1.28);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Folded Calicoflower', 3.02);
insert into Track (catalogueNo, trackName, trackLength) values (14, 'Burmann''s Basketgrass', 4.01);
insert into Track (catalogueNo, trackName, trackLength) values (55, 'Bluntleaf Sandwort', 3.5);
insert into Track (catalogueNo, trackName, trackLength) values (66, 'Creeping Bishop''s Cap', 2.1);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Abrothallus Lichen', 3.04);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Alberta Beardtongue', 5.2);
insert into Track (catalogueNo, trackName, trackLength) values (18, 'Ebony Sedge', 1.34);
insert into Track (catalogueNo, trackName, trackLength) values (81, 'Wedgeleaf Horkelia', 5.31);
insert into Track (catalogueNo, trackName, trackLength) values (7, 'Parsley', 3.42);
insert into Track (catalogueNo, trackName, trackLength) values (123, 'Shorthook Fishhook Cactus', 5.02);
insert into Track (catalogueNo, trackName, trackLength) values (30, 'Wedgeleaf Horkelia', 1.52);
insert into Track (catalogueNo, trackName, trackLength) values (50, 'Turkeypeas', 4.03);
insert into Track (catalogueNo, trackName, trackLength) values (44, 'Lewis River Suncup', 3.14);
insert into Track (catalogueNo, trackName, trackLength) values (114, 'Manchurian Monkshood', 2.33);
insert into Track (catalogueNo, trackName, trackLength) values (61, 'Carolina Bugbane', 3.31);
insert into Track (catalogueNo, trackName, trackLength) values (98, 'Slender Phlox', 5.36);
insert into Track (catalogueNo, trackName, trackLength) values (67, 'Tamarind', 3.16);
insert into Track (catalogueNo, trackName, trackLength) values (28, 'Common Whipplea', 5.37);
insert into Track (catalogueNo, trackName, trackLength) values (41, 'Smooth Fanpetals', 2.4);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'Fiddleleaf Tobacco', 4.42);
insert into Track (catalogueNo, trackName, trackLength) values (15, 'Sierra Tansymustard', 1.59);
insert into Track (catalogueNo, trackName, trackLength) values (127, 'Hachuela', 2.02);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Loxospora Lichen', 4.36);
insert into Track (catalogueNo, trackName, trackLength) values (28, 'Herbst''s Bur Cucumber', 2.14);
insert into Track (catalogueNo, trackName, trackLength) values (64, 'Sour Orange', 4.52);
insert into Track (catalogueNo, trackName, trackLength) values (38, 'Apalachicola St. Johnswort', 5.43);
insert into Track (catalogueNo, trackName, trackLength) values (88, 'Contra Costa Manzanita', 4.2);
insert into Track (catalogueNo, trackName, trackLength) values (38, 'Mendocino Spineflower', 1.24);
insert into Track (catalogueNo, trackName, trackLength) values (32, 'Erect Pricklypear', 1.35);
insert into Track (catalogueNo, trackName, trackLength) values (44, 'Jacob''s Dotted Lichen', 5.35);
insert into Track (catalogueNo, trackName, trackLength) values (124, 'Chelan Beardtongue', 3.56);
insert into Track (catalogueNo, trackName, trackLength) values (71, 'Canary Island St. Johnswort', 2.32);
insert into Track (catalogueNo, trackName, trackLength) values (95, 'Desert Woollystar', 4.2);
insert into Track (catalogueNo, trackName, trackLength) values (127, 'Venezuelan Panicgrass', 4.39);
insert into Track (catalogueNo, trackName, trackLength) values (102, 'Welsh Onion', 1.41);
insert into Track (catalogueNo, trackName, trackLength) values (40, 'Goldbloom Saxifrage', 2.58);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Eveningsnow', 2.17);
insert into Track (catalogueNo, trackName, trackLength) values (73, 'Streamside Phlox', 4.57);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'James'' Strigula Lichen', 5.06);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Uralanguis', 4.36);
insert into Track (catalogueNo, trackName, trackLength) values (118, 'Granite Mousetail', 4.42);
insert into Track (catalogueNo, trackName, trackLength) values (114, 'Puerto Rico Zephyrlily', 2.21);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Apalachicola Doll''s Daisy', 5.27);
insert into Track (catalogueNo, trackName, trackLength) values (127, 'Placidiopsis Lichen', 4.05);
insert into Track (catalogueNo, trackName, trackLength) values (67, 'Montagne''s Cartilage Lichen', 3.24);
insert into Track (catalogueNo, trackName, trackLength) values (4, 'Mealy Goosefoot', 5.05);
insert into Track (catalogueNo, trackName, trackLength) values (34, 'Cucumber Tree', 3.3);
insert into Track (catalogueNo, trackName, trackLength) values (75, 'Yellow Stingbush', 1.34);
insert into Track (catalogueNo, trackName, trackLength) values (56, 'Big Bend Foxtail Cactus', 3.05);
insert into Track (catalogueNo, trackName, trackLength) values (12, 'Flannelbush', 2.15);
insert into Track (catalogueNo, trackName, trackLength) values (110, 'Mountain Harebell', 3.3);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'Elephantear Pricklypear', 1.53);
insert into Track (catalogueNo, trackName, trackLength) values (70, 'Rocky Mountain Hemlockparsley', 3.19);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Lindheimera', 4.29);
insert into Track (catalogueNo, trackName, trackLength) values (43, 'Disc Lichen', 4.13);
insert into Track (catalogueNo, trackName, trackLength) values (89, 'Ruby Mountain Primrose', 3.02);
insert into Track (catalogueNo, trackName, trackLength) values (73, 'Bahia Piassaba Palm', 2.42);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Concentric Map Lichen', 5.01);
insert into Track (catalogueNo, trackName, trackLength) values (93, 'Needle Lichen', 3.09);
insert into Track (catalogueNo, trackName, trackLength) values (73, 'False Wheatgrass', 4.16);
insert into Track (catalogueNo, trackName, trackLength) values (44, 'Trapeliopsis Lichen', 2.08);
insert into Track (catalogueNo, trackName, trackLength) values (73, 'Pagosa Ipomopsis', 1.39);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Macoun''s Arthothelium Lichen', 1.28);
insert into Track (catalogueNo, trackName, trackLength) values (45, 'Cup Lichen', 1.52);
insert into Track (catalogueNo, trackName, trackLength) values (61, 'False Bird Of Paradise', 5.39);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Silky Phacelia', 5.19);
insert into Track (catalogueNo, trackName, trackLength) values (3, 'Feltleaf Violet', 2.06);
insert into Track (catalogueNo, trackName, trackLength) values (131, 'Flaxleaf Monardella', 2.33);
insert into Track (catalogueNo, trackName, trackLength) values (64, 'Rollins'' Cryptantha', 3.14);
insert into Track (catalogueNo, trackName, trackLength) values (56, 'Fritz''s Zeuxine', 5.08);
insert into Track (catalogueNo, trackName, trackLength) values (22, 'Lau Lihilihi', 3.51);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Needle Lichen', 4.25);
insert into Track (catalogueNo, trackName, trackLength) values (33, 'Schweinitz''s Waterweed', 2.15);
insert into Track (catalogueNo, trackName, trackLength) values (6, 'Roundtip Twinpod', 5.03);
insert into Track (catalogueNo, trackName, trackLength) values (49, 'Fruitleaf Knotweed', 2.39);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Rinodina Lichen', 2.09);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'Sematophyllum Moss', 3.56);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Torralbasia', 4.55);
insert into Track (catalogueNo, trackName, trackLength) values (40, 'Common Rush', 5.16);
insert into Track (catalogueNo, trackName, trackLength) values (118, 'Pearly Everlasting', 3.28);
insert into Track (catalogueNo, trackName, trackLength) values (117, 'Diverseleaf Small Limestone Moss', 3.35);
insert into Track (catalogueNo, trackName, trackLength) values (47, 'Skunkcabbage', 4.29);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Goldbloom Saxifrage', 5.04);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Manyray Aster', 4.45);
insert into Track (catalogueNo, trackName, trackLength) values (3, 'Chamise', 2.03);
insert into Track (catalogueNo, trackName, trackLength) values (63, 'Field Sowthistle', 5.32);
insert into Track (catalogueNo, trackName, trackLength) values (70, 'Heterocarpon Lichen', 3.38);
insert into Track (catalogueNo, trackName, trackLength) values (19, 'Hymenopappus', 3.32);
insert into Track (catalogueNo, trackName, trackLength) values (109, 'Prickly Hornwort', 3.32);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'James'' Sedge', 1.54);
insert into Track (catalogueNo, trackName, trackLength) values (2, 'Threeleaf Foamflower', 5.35);
insert into Track (catalogueNo, trackName, trackLength) values (83, 'Avens', 3.48);
insert into Track (catalogueNo, trackName, trackLength) values (122, 'Lecidella Lichen', 2.39);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Hybrid Pitcherplant', 2.04);
insert into Track (catalogueNo, trackName, trackLength) values (93, 'Pacific Woodfern', 5.03);
insert into Track (catalogueNo, trackName, trackLength) values (125, 'Largefruit Catchfly', 4.29);
insert into Track (catalogueNo, trackName, trackLength) values (52, 'Sheldon''s Milkvetch', 3.39);
insert into Track (catalogueNo, trackName, trackLength) values (106, 'Wedge Beggarticks', 5.32);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'Elmer''s Lupine', 3.51);
insert into Track (catalogueNo, trackName, trackLength) values (39, 'Marantochloa', 3.38);
insert into Track (catalogueNo, trackName, trackLength) values (119, 'Wigandia', 2.13);
insert into Track (catalogueNo, trackName, trackLength) values (42, 'Maple', 3.58);
insert into Track (catalogueNo, trackName, trackLength) values (16, 'Eastern Fox Sedge', 3.34);
insert into Track (catalogueNo, trackName, trackLength) values (16, 'Dietes', 1.23);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'Ribbed Murainagrass', 3.28);
insert into Track (catalogueNo, trackName, trackLength) values (65, 'Leggett''s Pinweed', 2.19);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Spotted Beebalm', 1.38);
insert into Track (catalogueNo, trackName, trackLength) values (14, 'Chilean Bird''s-foot Trefoil', 2.51);
insert into Track (catalogueNo, trackName, trackLength) values (121, 'Smallflower Lovegrass', 4.54);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'Syrrhopodon Moss', 3.05);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Pitchfork Crowngrass', 3.05);
insert into Track (catalogueNo, trackName, trackLength) values (18, 'Whitehair Rosette Grass', 5.33);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Bulrush', 2.48);
insert into Track (catalogueNo, trackName, trackLength) values (55, 'Panamint Beardtongue', 5.1);
insert into Track (catalogueNo, trackName, trackLength) values (111, 'Velvetleaf', 5.3);
insert into Track (catalogueNo, trackName, trackLength) values (104, 'Florida Tasselflower', 2.29);
insert into Track (catalogueNo, trackName, trackLength) values (23, 'Winter''s Bark', 4.42);
insert into Track (catalogueNo, trackName, trackLength) values (107, 'Guadeloupe Bog Orchid', 2.39);
insert into Track (catalogueNo, trackName, trackLength) values (32, 'Rough Cryptantha', 1.34);
insert into Track (catalogueNo, trackName, trackLength) values (65, 'Bright Green Spikerush', 4.56);
insert into Track (catalogueNo, trackName, trackLength) values (23, 'Thistle', 2.32);
insert into Track (catalogueNo, trackName, trackLength) values (43, 'Bunch Cutgrass', 2.49);
insert into Track (catalogueNo, trackName, trackLength) values (120, 'Parish''s Bluecurls', 1.36);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'Gloria De La Manana', 2.16);
insert into Track (catalogueNo, trackName, trackLength) values (98, 'Harvey''s Beaksedge', 5.39);
insert into Track (catalogueNo, trackName, trackLength) values (97, 'Woodland Climbing Bamboo', 2.19);
insert into Track (catalogueNo, trackName, trackLength) values (32, 'Pongame Oiltree', 1.56);
insert into Track (catalogueNo, trackName, trackLength) values (75, 'Condorvine', 1.55);
insert into Track (catalogueNo, trackName, trackLength) values (26, 'Wideflower Phlox', 3.35);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Pennsylvania Rush', 4.23);
insert into Track (catalogueNo, trackName, trackLength) values (96, 'Bogrush', 3.29);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Swallen''s Needlegrass', 1.54);
insert into Track (catalogueNo, trackName, trackLength) values (130, 'Spotted Sandmat', 3.33);
insert into Track (catalogueNo, trackName, trackLength) values (10, 'Derris', 3.29);
insert into Track (catalogueNo, trackName, trackLength) values (83, 'Rocky Mountain Indian Parsley', 2.13);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'Caparosa', 3.46);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Bushy Goldentop', 5.44);
insert into Track (catalogueNo, trackName, trackLength) values (27, 'Dune Tetramolopium', 2.35);
insert into Track (catalogueNo, trackName, trackLength) values (84, 'Sleepy Silene', 3.45);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Muhlenberg''s Centaury', 3.13);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Panamint Beardtongue', 2.27);
insert into Track (catalogueNo, trackName, trackLength) values (78, 'Stinging Nettle', 4.29);
insert into Track (catalogueNo, trackName, trackLength) values (85, 'Wart Lichen', 3.5);
insert into Track (catalogueNo, trackName, trackLength) values (89, 'West African Rubbertree', 2.01);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Northland Cottonsedge', 3.34);
insert into Track (catalogueNo, trackName, trackLength) values (64, 'Boykin''s Milkwort', 2.19);
insert into Track (catalogueNo, trackName, trackLength) values (89, 'Desert Mountain Mock Orange', 3.25);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Indian Long Pepper', 3.36);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Gray Alder', 2.25);
insert into Track (catalogueNo, trackName, trackLength) values (23, 'Clusterleaf', 4.41);
insert into Track (catalogueNo, trackName, trackLength) values (72, 'Rayless Sunflower', 2.55);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Sphaerophysa', 5.36);
insert into Track (catalogueNo, trackName, trackLength) values (2, 'Tall Albizia', 3.38);
insert into Track (catalogueNo, trackName, trackLength) values (132, 'Presidio Clarkia', 2.5);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Hairy Indian Paintbrush', 4.44);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Dalechampia', 2.52);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Sunflower', 1.45);
insert into Track (catalogueNo, trackName, trackLength) values (67, 'Phlox', 3);
insert into Track (catalogueNo, trackName, trackLength) values (120, 'Callaeum', 5.11);
insert into Track (catalogueNo, trackName, trackLength) values (34, 'Iranian Knapweed', 4.53);
insert into Track (catalogueNo, trackName, trackLength) values (128, 'Oregon Whitetop Aster', 1.28);
insert into Track (catalogueNo, trackName, trackLength) values (20, 'Prairie Spiderwort', 3.32);
insert into Track (catalogueNo, trackName, trackLength) values (7, 'Soft Fox Sedge', 2);
insert into Track (catalogueNo, trackName, trackLength) values (88, 'Floating Primrose-willow', 4.21);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Scarlet Cinquefoil', 5.34);
insert into Track (catalogueNo, trackName, trackLength) values (102, 'Bryohaplocladium Moss', 4.46);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'Sloughgrass', 3.08);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Green Dragon', 4.51);
insert into Track (catalogueNo, trackName, trackLength) values (57, 'Chocolate Vine', 2.19);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Silver Fleabane', 2.04);
insert into Track (catalogueNo, trackName, trackLength) values (130, 'Fall Dandelion', 3.18);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'Common Woolly Sunflower', 1.52);
insert into Track (catalogueNo, trackName, trackLength) values (28, 'Dyebush', 4.5);
insert into Track (catalogueNo, trackName, trackLength) values (128, 'California Pinefoot', 3.3);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'California Horkelia', 4.33);
insert into Track (catalogueNo, trackName, trackLength) values (24, 'Mountain Stitchwort', 2.55);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Cape Primrose', 4.34);
insert into Track (catalogueNo, trackName, trackLength) values (86, 'Heartleaf Skullcap', 1.4);
insert into Track (catalogueNo, trackName, trackLength) values (93, 'Pigmy Cypress-pine', 4.28);
insert into Track (catalogueNo, trackName, trackLength) values (54, 'Carbonea Lichen', 4.26);
insert into Track (catalogueNo, trackName, trackLength) values (7, 'Dogwood', 3.59);
insert into Track (catalogueNo, trackName, trackLength) values (130, 'Membranous Garlicvine', 4.46);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Naked Mexicanhat', 4.57);
insert into Track (catalogueNo, trackName, trackLength) values (40, 'American Lotus', 5.17);
insert into Track (catalogueNo, trackName, trackLength) values (126, 'Common Selfheal', 5.13);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Cottonwood Springs Suncup', 4.08);
insert into Track (catalogueNo, trackName, trackLength) values (15, 'Stream Currant', 5.05);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Tansyleaf Nightshade', 2.52);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Nihoa Pritchardia', 1.23);
insert into Track (catalogueNo, trackName, trackLength) values (22, 'Allegheny Stonecrop', 4.54);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Candytuft', 1.3);
insert into Track (catalogueNo, trackName, trackLength) values (45, 'White Sands Fanmustard', 4.03);
insert into Track (catalogueNo, trackName, trackLength) values (34, 'False Baby''s Breath', 2.54);
insert into Track (catalogueNo, trackName, trackLength) values (37, 'Guatemalan Gamagrass', 3.56);
insert into Track (catalogueNo, trackName, trackLength) values (101, 'Rim Lichen', 4.34);
insert into Track (catalogueNo, trackName, trackLength) values (106, 'Fissure Dot Lichen', 1.31);
insert into Track (catalogueNo, trackName, trackLength) values (5, 'Pholisma', 1.43);
insert into Track (catalogueNo, trackName, trackLength) values (42, 'Thinleaved Owl''s-clover', 2.34);
insert into Track (catalogueNo, trackName, trackLength) values (44, 'King''s Gold', 1.24);
insert into Track (catalogueNo, trackName, trackLength) values (96, 'Sunburst', 4.04);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Crabseye Lichen', 4.57);
insert into Track (catalogueNo, trackName, trackLength) values (20, 'Pereskia', 3.38);
insert into Track (catalogueNo, trackName, trackLength) values (107, 'Pyrenopsis Lichen', 1.57);
insert into Track (catalogueNo, trackName, trackLength) values (4, 'Cuban Jute', 2.18);
insert into Track (catalogueNo, trackName, trackLength) values (91, 'Silverpuffs', 2.18);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Soapweed Yucca', 4.34);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'Acaena', 5.24);
insert into Track (catalogueNo, trackName, trackLength) values (30, 'Bingen Lupine', 1.46);
insert into Track (catalogueNo, trackName, trackLength) values (88, 'Corkscrew Beggarticks', 5.03);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Ahart''s Cluster Rose', 3.46);
insert into Track (catalogueNo, trackName, trackLength) values (18, 'Gray Goldenrod', 5.18);
insert into Track (catalogueNo, trackName, trackLength) values (79, 'Rigid Whitetop Aster', 4.13);
insert into Track (catalogueNo, trackName, trackLength) values (107, 'Stiff Pea', 3.17);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Pylaes'' Sphagnum', 2.12);
insert into Track (catalogueNo, trackName, trackLength) values (129, 'Springblossom', 1.43);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Short''s Goldenrod', 2.53);
insert into Track (catalogueNo, trackName, trackLength) values (105, 'Peruvian Ragweed', 4);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'New Mexico Rockdaisy', 5.27);
insert into Track (catalogueNo, trackName, trackLength) values (120, 'Curly Dock', 1.38);
insert into Track (catalogueNo, trackName, trackLength) values (110, 'Coulter''s Goldfields', 1.58);
insert into Track (catalogueNo, trackName, trackLength) values (129, 'Kenwood Marsh Checkerbloom', 1.55);
insert into Track (catalogueNo, trackName, trackLength) values (118, 'Western Bog Aster', 1.28);
insert into Track (catalogueNo, trackName, trackLength) values (106, 'Silky Silverbush', 3.37);
insert into Track (catalogueNo, trackName, trackLength) values (111, 'Alpine Saxifrage', 3.22);
insert into Track (catalogueNo, trackName, trackLength) values (74, 'Polyalthia', 3);
insert into Track (catalogueNo, trackName, trackLength) values (56, 'Rosette Lichen', 4.42);
insert into Track (catalogueNo, trackName, trackLength) values (72, 'Chinese Rose', 3.24);
insert into Track (catalogueNo, trackName, trackLength) values (80, 'Cup Lichen', 3.19);
insert into Track (catalogueNo, trackName, trackLength) values (37, 'Boreal Primrose', 2.05);
insert into Track (catalogueNo, trackName, trackLength) values (82, 'Trinity Mountain Rockcress', 5.22);
insert into Track (catalogueNo, trackName, trackLength) values (90, 'Rainbow Pink', 4.03);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Smallheaded Townsend Daisy', 3.56);
insert into Track (catalogueNo, trackName, trackLength) values (91, 'Sedge', 2.41);
insert into Track (catalogueNo, trackName, trackLength) values (45, 'California Pseudobraunia Moss', 4.42);
insert into Track (catalogueNo, trackName, trackLength) values (104, 'Mountain Fly Honeysuckle', 4.21);
insert into Track (catalogueNo, trackName, trackLength) values (61, 'Hawkweed', 2.21);
insert into Track (catalogueNo, trackName, trackLength) values (57, 'Taperleaf Water Horehound', 4.38);
insert into Track (catalogueNo, trackName, trackLength) values (1, 'Coamo River Pouzolzsbush', 1.53);
insert into Track (catalogueNo, trackName, trackLength) values (30, 'Whiteflower Passionflower', 5.22);
insert into Track (catalogueNo, trackName, trackLength) values (131, 'Eschscholtz''s Hairy Rockcress', 2.21);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Sunflower', 1.39);
insert into Track (catalogueNo, trackName, trackLength) values (88, 'Elmleaf Blackberry', 2.33);
insert into Track (catalogueNo, trackName, trackLength) values (81, 'Lobed Tickseed', 1.25);
insert into Track (catalogueNo, trackName, trackLength) values (121, 'Thicket Dewberry', 1.55);
insert into Track (catalogueNo, trackName, trackLength) values (103, 'Coffee Cliffbrake', 3.15);
insert into Track (catalogueNo, trackName, trackLength) values (103, 'Whip Pussytoes', 4.37);
insert into Track (catalogueNo, trackName, trackLength) values (75, 'Snow Lichen', 5.39);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Slender Grasswort', 4.08);
insert into Track (catalogueNo, trackName, trackLength) values (130, 'Cup Lichen', 2);
insert into Track (catalogueNo, trackName, trackLength) values (106, 'Tall Silverbush', 1.47);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Tundra Alkaligrass', 3.59);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'Longbeard Mariposa Lily', 5.2);
insert into Track (catalogueNo, trackName, trackLength) values (18, 'Lemmon''s Onion', 4.1);
insert into Track (catalogueNo, trackName, trackLength) values (57, 'Wildrye', 1.25);
insert into Track (catalogueNo, trackName, trackLength) values (70, 'Peruvian Zinnia', 2.53);
insert into Track (catalogueNo, trackName, trackLength) values (6, 'Littleleaf Buckbrush', 3.36);
insert into Track (catalogueNo, trackName, trackLength) values (1, 'Ackerman''s Milkvetch', 3.24);
insert into Track (catalogueNo, trackName, trackLength) values (57, 'Hoffmann''s Nightshade', 2.39);
insert into Track (catalogueNo, trackName, trackLength) values (69, 'Florida Keys Sage', 5.27);
insert into Track (catalogueNo, trackName, trackLength) values (19, 'Schott''s Calico', 2.14);
insert into Track (catalogueNo, trackName, trackLength) values (81, 'Curlytop Gumweed', 3.59);
insert into Track (catalogueNo, trackName, trackLength) values (47, 'Japanese Pachysandra', 2.06);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Hairy Grey Heather', 3.49);
insert into Track (catalogueNo, trackName, trackLength) values (111, 'Hairy Pinweed', 2.39);
insert into Track (catalogueNo, trackName, trackLength) values (65, 'Colombian Bluestem', 1.25);
insert into Track (catalogueNo, trackName, trackLength) values (92, 'Phaeocalicium Lichen', 3.12);
insert into Track (catalogueNo, trackName, trackLength) values (17, 'Youth On Age', 4.38);
insert into Track (catalogueNo, trackName, trackLength) values (24, 'Coastal Carolina Spiderlily', 2.22);
insert into Track (catalogueNo, trackName, trackLength) values (126, 'Perennial Blazingstar', 2.06);
insert into Track (catalogueNo, trackName, trackLength) values (84, 'Seward''s Blackberry', 3.1);
insert into Track (catalogueNo, trackName, trackLength) values (37, 'Paperbush', 4.27);
insert into Track (catalogueNo, trackName, trackLength) values (37, 'Prostrate Ceanothus', 3.32);
insert into Track (catalogueNo, trackName, trackLength) values (79, 'Timber Milkvetch', 3.2);
insert into Track (catalogueNo, trackName, trackLength) values (2, 'Tarweed', 2.57);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'Mock Fanpetals', 4.57);
insert into Track (catalogueNo, trackName, trackLength) values (18, 'Slimspike Threeawn', 3.31);
insert into Track (catalogueNo, trackName, trackLength) values (124, 'Rio Grande Butterflybush', 4.22);
insert into Track (catalogueNo, trackName, trackLength) values (134, 'Scribble Lichen', 4.1);
insert into Track (catalogueNo, trackName, trackLength) values (77, 'Sea Rosemary', 4.1);
insert into Track (catalogueNo, trackName, trackLength) values (79, 'Hairy Honeysuckle', 4.27);
insert into Track (catalogueNo, trackName, trackLength) values (116, 'Purple Chinese Houses', 3.33);
insert into Track (catalogueNo, trackName, trackLength) values (36, 'Maui Phyllostegia', 5.08);
insert into Track (catalogueNo, trackName, trackLength) values (80, 'Parasite Rinodina Lichen', 2.31);
insert into Track (catalogueNo, trackName, trackLength) values (48, 'Hawai''i Cheesewood', 3.13);
insert into Track (catalogueNo, trackName, trackLength) values (28, 'Dwarf Bamboo', 1.52);
insert into Track (catalogueNo, trackName, trackLength) values (131, 'Santa Catalina Island Bedstraw', 4.45);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Lacespine Nipple Cactus', 3.32);
insert into Track (catalogueNo, trackName, trackLength) values (78, 'Hideseed', 4.32);
insert into Track (catalogueNo, trackName, trackLength) values (33, 'Southern Pea', 5.27);
insert into Track (catalogueNo, trackName, trackLength) values (124, 'Forest Peperomia', 3.37);
insert into Track (catalogueNo, trackName, trackLength) values (21, 'Hollyleaf Bur Ragweed', 3.31);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Woolly Locoweed', 3.12);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Spleenwort', 5.37);
insert into Track (catalogueNo, trackName, trackLength) values (98, 'Sweetshrub', 2.4);
insert into Track (catalogueNo, trackName, trackLength) values (18, '''ohi''a Lehua', 4.18);
insert into Track (catalogueNo, trackName, trackLength) values (25, 'Silky Silverbush', 4.16);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Kennedy''s Milkvetch', 4.26);
insert into Track (catalogueNo, trackName, trackLength) values (79, 'Glare Snow Lichen', 5.35);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'Pyxine Lichen', 1.35);
insert into Track (catalogueNo, trackName, trackLength) values (21, 'Rock Nettle', 4.06);
insert into Track (catalogueNo, trackName, trackLength) values (133, 'Sea Sedge', 3.54);
insert into Track (catalogueNo, trackName, trackLength) values (99, 'Sand Pine', 2.33);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Lathberry', 4.49);
insert into Track (catalogueNo, trackName, trackLength) values (22, 'Northern Bog Sedge', 1.39);
insert into Track (catalogueNo, trackName, trackLength) values (71, 'Myurella Moss', 4.05);
insert into Track (catalogueNo, trackName, trackLength) values (102, 'Peace Lily', 2.05);
insert into Track (catalogueNo, trackName, trackLength) values (114, 'Broom Teatree', 3.13);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'Rodwood', 4.18);
insert into Track (catalogueNo, trackName, trackLength) values (130, 'Winterberry Euonymus', 1.39);
insert into Track (catalogueNo, trackName, trackLength) values (132, 'Water Knotweed', 3.2);
insert into Track (catalogueNo, trackName, trackLength) values (131, 'African Bermudagrass', 4.02);
insert into Track (catalogueNo, trackName, trackLength) values (47, 'Western Sandparsley', 5.35);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'Gmelin''s Saltbush', 2.46);
insert into Track (catalogueNo, trackName, trackLength) values (45, 'Black Sagebrush', 2.44);
insert into Track (catalogueNo, trackName, trackLength) values (82, 'Shy Wallflower', 4.42);
insert into Track (catalogueNo, trackName, trackLength) values (23, 'Lansium', 2.27);
insert into Track (catalogueNo, trackName, trackLength) values (117, 'Woolly Bird''s-foot Trefoil', 2.5);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'Milkflower Willowherb', 5.24);
insert into Track (catalogueNo, trackName, trackLength) values (114, 'Modest Prickle Grass', 2.28);
insert into Track (catalogueNo, trackName, trackLength) values (105, 'Lacy Germander', 4.06);
insert into Track (catalogueNo, trackName, trackLength) values (29, 'Myoporum', 2.21);
insert into Track (catalogueNo, trackName, trackLength) values (84, 'Lanceleaf Arnica', 3.24);
insert into Track (catalogueNo, trackName, trackLength) values (121, 'Climbing Rose', 3.49);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Meadow Bistort', 3.56);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Broadleaf Monkeyflower', 2.34);
insert into Track (catalogueNo, trackName, trackLength) values (111, 'Darkmargin Rim Lichen', 2.31);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Yellowstone Draba', 2.25);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Secund Jewelflower', 2.34);
insert into Track (catalogueNo, trackName, trackLength) values (54, 'Swamp Colicwood', 3.42);
insert into Track (catalogueNo, trackName, trackLength) values (47, 'Manyflower Tobacco', 5.29);
insert into Track (catalogueNo, trackName, trackLength) values (40, 'Sticky Tofieldia', 2.07);
insert into Track (catalogueNo, trackName, trackLength) values (96, 'Cockerell''s Stonecrop', 4.36);
insert into Track (catalogueNo, trackName, trackLength) values (107, 'Serrulate Penstemon', 4.47);
insert into Track (catalogueNo, trackName, trackLength) values (69, 'Diffuseflower Evening Primrose', 1.3);
insert into Track (catalogueNo, trackName, trackLength) values (42, 'Cup Lichen', 1.35);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'Buckley''s Dropseed', 2.09);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Cricketvine', 1.51);
insert into Track (catalogueNo, trackName, trackLength) values (45, 'Southern Globethistle', 5.35);
insert into Track (catalogueNo, trackName, trackLength) values (132, 'Trichodon Moss', 2.05);
insert into Track (catalogueNo, trackName, trackLength) values (101, 'Thelidium Lichen', 3.51);
insert into Track (catalogueNo, trackName, trackLength) values (18, 'Lambsquarters', 4.24);
insert into Track (catalogueNo, trackName, trackLength) values (24, 'Pelicanflower', 4.44);
insert into Track (catalogueNo, trackName, trackLength) values (6, 'Turtlehead', 4.58);
insert into Track (catalogueNo, trackName, trackLength) values (55, 'Woad', 2.28);
insert into Track (catalogueNo, trackName, trackLength) values (99, 'Foliage Flower', 1.26);
insert into Track (catalogueNo, trackName, trackLength) values (75, 'Heartleaf Maiden Fern', 4.05);
insert into Track (catalogueNo, trackName, trackLength) values (125, 'Cylindricfruit Primrose-willow', 5.04);
insert into Track (catalogueNo, trackName, trackLength) values (27, 'Inchplant', 3);
insert into Track (catalogueNo, trackName, trackLength) values (23, 'Kauai Bloodgrass', 5.23);
insert into Track (catalogueNo, trackName, trackLength) values (61, 'Mohr''s Bluestem', 2.36);
insert into Track (catalogueNo, trackName, trackLength) values (81, 'Camwood', 1.31);
insert into Track (catalogueNo, trackName, trackLength) values (134, 'False Mastic', 1.59);
insert into Track (catalogueNo, trackName, trackLength) values (103, 'Rougeplant', 2.2);
insert into Track (catalogueNo, trackName, trackLength) values (124, 'Red Bulrush', 2.58);
insert into Track (catalogueNo, trackName, trackLength) values (41, 'Serpentine Savory', 5.32);
insert into Track (catalogueNo, trackName, trackLength) values (104, 'Miami Mist', 1.35);
insert into Track (catalogueNo, trackName, trackLength) values (53, 'Arctoparmelia Lichen', 3.21);
insert into Track (catalogueNo, trackName, trackLength) values (105, 'Ceylon Gooseberry', 4.01);
insert into Track (catalogueNo, trackName, trackLength) values (10, 'Broadfruit Mariposa Lily', 2.56);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Pale Madwort', 4.5);
insert into Track (catalogueNo, trackName, trackLength) values (93, 'Bolander''s Mock Dandelion', 2.52);
insert into Track (catalogueNo, trackName, trackLength) values (83, 'Spanish Lupine', 4.06);
insert into Track (catalogueNo, trackName, trackLength) values (50, 'Lacy Germander', 5.23);
insert into Track (catalogueNo, trackName, trackLength) values (79, 'Barringtonia', 3.59);
insert into Track (catalogueNo, trackName, trackLength) values (27, 'Orcutt''s Foxtail Cactus', 1.55);
insert into Track (catalogueNo, trackName, trackLength) values (88, 'Didymodon Moss', 3.02);
insert into Track (catalogueNo, trackName, trackLength) values (33, 'Annual Marsh Elder', 2.13);
insert into Track (catalogueNo, trackName, trackLength) values (3, 'Creeping Tonguefern', 3.37);
insert into Track (catalogueNo, trackName, trackLength) values (38, 'Stigmidium Lichen', 1.41);
insert into Track (catalogueNo, trackName, trackLength) values (133, 'Sainfoin', 5.14);
insert into Track (catalogueNo, trackName, trackLength) values (115, 'Ketona Tickseed', 2.25);
insert into Track (catalogueNo, trackName, trackLength) values (3, 'Atrichum Moss', 2.45);
insert into Track (catalogueNo, trackName, trackLength) values (44, 'Wailua River Yellow Loosestrife', 2.05);
insert into Track (catalogueNo, trackName, trackLength) values (118, 'Wolf''s Opuntia', 2.09);
insert into Track (catalogueNo, trackName, trackLength) values (94, 'Shieldplant', 1.34);
insert into Track (catalogueNo, trackName, trackLength) values (26, 'Pammel''s Oniongrass', 4.06);
insert into Track (catalogueNo, trackName, trackLength) values (30, 'Wharton''s Dewberry', 2.17);
insert into Track (catalogueNo, trackName, trackLength) values (110, 'West Indian Milkwort', 2.11);
insert into Track (catalogueNo, trackName, trackLength) values (99, 'Menzies'' Pepperweed', 3.21);
insert into Track (catalogueNo, trackName, trackLength) values (106, 'Tapellaria Lichen', 1.42);
insert into Track (catalogueNo, trackName, trackLength) values (43, 'Coahuila Blazingstar', 2.55);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Catalina Nightshade', 2.38);
insert into Track (catalogueNo, trackName, trackLength) values (95, 'Churchill Narrows Buckwheat', 1.24);
insert into Track (catalogueNo, trackName, trackLength) values (98, 'Palespike Lobelia', 1.5);
insert into Track (catalogueNo, trackName, trackLength) values (26, 'Leafbract', 1.32);
insert into Track (catalogueNo, trackName, trackLength) values (49, 'Amaryllis', 2.14);
insert into Track (catalogueNo, trackName, trackLength) values (8, 'Piedmont Meadow-rue', 4.59);
insert into Track (catalogueNo, trackName, trackLength) values (5, 'Tepary Bean', 3.29);
insert into Track (catalogueNo, trackName, trackLength) values (119, 'Hairy Dozedaisy', 4.43);
insert into Track (catalogueNo, trackName, trackLength) values (76, 'Erythrina', 2.55);
insert into Track (catalogueNo, trackName, trackLength) values (59, 'Stinking Milkvetch', 4.35);
insert into Track (catalogueNo, trackName, trackLength) values (31, 'American False Pennyroyal', 4.18);
insert into Track (catalogueNo, trackName, trackLength) values (7, 'Cow Itch Tree', 5.13);
insert into Track (catalogueNo, trackName, trackLength) values (37, 'Lacefern', 3.53);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Black Willow', 3.05);
insert into Track (catalogueNo, trackName, trackLength) values (87, 'Cupped Monolopia', 2.32);
insert into Track (catalogueNo, trackName, trackLength) values (95, 'Dodge''s Hawthorn', 3.33);
insert into Track (catalogueNo, trackName, trackLength) values (63, 'Silkgrass', 2.08);
insert into Track (catalogueNo, trackName, trackLength) values (111, 'Cayratia', 1.4);
insert into Track (catalogueNo, trackName, trackLength) values (39, 'Rim Lichen', 2.34);
insert into Track (catalogueNo, trackName, trackLength) values (77, 'Calico Aster', 1.52);
insert into Track (catalogueNo, trackName, trackLength) values (96, 'Muhlenberg''s Funaria Moss', 4.21);
insert into Track (catalogueNo, trackName, trackLength) values (73, 'Xanthoparmelia Lichen', 3.14);
insert into Track (catalogueNo, trackName, trackLength) values (48, 'Buckwheat', 1.24);
insert into Track (catalogueNo, trackName, trackLength) values (133, 'Sunfacing Coneflower', 4.15);
insert into Track (catalogueNo, trackName, trackLength) values (92, 'California Lacefern', 5.09);
insert into Track (catalogueNo, trackName, trackLength) values (123, 'Maui Tetramolopium', 4.01);
insert into Track (catalogueNo, trackName, trackLength) values (7, 'Needle Lichen', 2.08);
insert into Track (catalogueNo, trackName, trackLength) values (62, 'Ditch Stonecrop', 1.23);
insert into Track (catalogueNo, trackName, trackLength) values (70, 'Hawai''i Hala Pepe', 1.32);
insert into Track (catalogueNo, trackName, trackLength) values (55, 'Sugarberry', 5.16);
insert into Track (catalogueNo, trackName, trackLength) values (44, 'Esslingeriana Lichen', 2.53);
insert into Track (catalogueNo, trackName, trackLength) values (99, 'Mamani', 4.46);
insert into Track (catalogueNo, trackName, trackLength) values (81, 'Bigelow Sage', 4.35);
insert into Track (catalogueNo, trackName, trackLength) values (67, 'Neoregelia', 3.2);
insert into Track (catalogueNo, trackName, trackLength) values (14, 'Dwarf Spikemoss', 3.1);
insert into Track (catalogueNo, trackName, trackLength) values (5, 'Bactris Palm', 5.32);
insert into Track (catalogueNo, trackName, trackLength) values (110, 'California Stickseed', 1.24);
insert into Track (catalogueNo, trackName, trackLength) values (103, 'Lobularia', 1.3);
insert into Track (catalogueNo, trackName, trackLength) values (68, 'Crabseye Lichen', 2.07);
insert into Track (catalogueNo, trackName, trackLength) values (81, 'Piedmont Bladderwort', 5.3);
insert into Track (catalogueNo, trackName, trackLength) values (92, 'Fall Goldenrod', 1.33);
insert into Track (catalogueNo, trackName, trackLength) values (83, 'Openground Dewberry', 4.21);
insert into Track (catalogueNo, trackName, trackLength) values (49, 'Alkali Sandmat', 5.13);
insert into Track (catalogueNo, trackName, trackLength) values (112, 'Candle Snuffer Moss', 4);
insert into Track (catalogueNo, trackName, trackLength) values (116, 'Sagebrush Cholla', 5.37);
insert into Track (catalogueNo, trackName, trackLength) values (27, 'Pitcherplant', 1.41);
insert into Track (catalogueNo, trackName, trackLength) values (49, 'Redding Buckwheat', 1.26);
insert into Track (catalogueNo, trackName, trackLength) values (21, 'White Pricklyash', 1.28);
insert into Track (catalogueNo, trackName, trackLength) values (45, 'Snowqueen', 5.22);
insert into Track (catalogueNo, trackName, trackLength) values (99, 'Scurfymallow', 3.38);
insert into Track (catalogueNo, trackName, trackLength) values (95, 'Mountain St. Johnswort', 4.28);
insert into Track (catalogueNo, trackName, trackLength) values (60, 'Midland Fawnlily', 3.56);
insert into Track (catalogueNo, trackName, trackLength) values (4, 'Clover''s Vervain', 1.45);
insert into Track (catalogueNo, trackName, trackLength) values (109, 'Woolgrass', 5.4);
insert into Track (catalogueNo, trackName, trackLength) values (111, 'Least Adderstongue', 3.59);
insert into Track (catalogueNo, trackName, trackLength) values (100, 'Red Star-thistle', 1.28);
insert into Track (catalogueNo, trackName, trackLength) values (125, 'Peaty Dewberry', 1.59);
insert into Track (catalogueNo, trackName, trackLength) values (9, 'Blacklancewood', 2.11);
insert into Track (catalogueNo, trackName, trackLength) values (51, 'Murray''s Rockcress', 4.01);
insert into Track (catalogueNo, trackName, trackLength) values (57, 'Aztec Gilia', 3.25);
insert into Track (catalogueNo, trackName, trackLength) values (114, 'Mosquito Flatsedge', 2.56);
insert into Track (catalogueNo, trackName, trackLength) values (90, 'Nehe', 3.58);
insert into Track (catalogueNo, trackName, trackLength) values (94, 'Mt. Waialeale Island-daisy', 3.51);
insert into Track (catalogueNo, trackName, trackLength) values (122, 'Menzies'' Goldenbush', 2.46);
insert into Track (catalogueNo, trackName, trackLength) values (128, 'Fivepetal Leaf-flower', 4.59);
insert into Track (catalogueNo, trackName, trackLength) values (13, 'Shortleaved Sedge', 4.12);
insert into Track (catalogueNo, trackName, trackLength) values (28, 'Appalachian Fissidens Moss', 5.4);
insert into Track (catalogueNo, trackName, trackLength) values (130, 'California Bog Asphodel', 5.42);
insert into Track (catalogueNo, trackName, trackLength) values (5, 'Pygmy Poppy', 3.58);
insert into Track (catalogueNo, trackName, trackLength) values (41, 'Rimmed Lichen', 4.3);
insert into Track (catalogueNo, trackName, trackLength) values (97, 'Brothera Moss', 4.17);
insert into Track (catalogueNo, trackName, trackLength) values (35, 'Wayside Aster', 3.58);
insert into Track (catalogueNo, trackName, trackLength) values (104, 'Bengal Trumpet', 3.3);
insert into Track (catalogueNo, trackName, trackLength) values (47, 'River Broom-rape', 3.26);
insert into Track (catalogueNo, trackName, trackLength) values (90, 'German-madwort', 5.33);
insert into Track (catalogueNo, trackName, trackLength) values (52, 'Plainsdaisy', 1.46);
